// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_filesystem_0_2_0_types

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_clocks_0_2_0_wall_clock"
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_io_0_2_0_error"
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_io_0_2_0_streams"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type InputStream = wasi_io_0_2_0_streams.InputStream
type OutputStream = wasi_io_0_2_0_streams.OutputStream
type Error = wasi_io_0_2_0_error.Error
type Datetime = wasi_clocks_0_2_0_wall_clock.Datetime

// File size or length of a region within a file.
type Filesize = uint64

const (
	// The type of the descriptor or file is unknown or is different from
	// any of the other types specified.
	DescriptorTypeUnknown uint8 = 0
	// The descriptor refers to a block device inode.
	DescriptorTypeBlockDevice uint8 = 1
	// The descriptor refers to a character device inode.
	DescriptorTypeCharacterDevice uint8 = 2
	// The descriptor refers to a directory inode.
	DescriptorTypeDirectory uint8 = 3
	// The descriptor refers to a named pipe.
	DescriptorTypeFifo uint8 = 4
	// The file refers to a symbolic link inode.
	DescriptorTypeSymbolicLink uint8 = 5
	// The descriptor refers to a regular file inode.
	DescriptorTypeRegularFile uint8 = 6
	// The descriptor refers to a socket.
	DescriptorTypeSocket uint8 = 7
)

// The type of a filesystem object referenced by a descriptor.
//
// Note: This was called `filetype` in earlier versions of WASI.
type DescriptorType = uint8

const (
	// Read mode: Data can be read.
	DescriptorFlagsRead uint8 = 1 << 0
	// Write mode: Data can be written to.
	DescriptorFlagsWrite uint8 = 1 << 1
	// Request that writes be performed according to synchronized I/O file
	// integrity completion. The data stored in the file and the file's
	// metadata are synchronized. This is similar to `O_SYNC` in POSIX.
	//
	// The precise semantics of this operation have not yet been defined for
	// WASI. At this time, it should be interpreted as a request, and not a
	// requirement.
	DescriptorFlagsFileIntegritySync uint8 = 1 << 2
	// Request that writes be performed according to synchronized I/O data
	// integrity completion. Only the data stored in the file is
	// synchronized. This is similar to `O_DSYNC` in POSIX.
	//
	// The precise semantics of this operation have not yet been defined for
	// WASI. At this time, it should be interpreted as a request, and not a
	// requirement.
	DescriptorFlagsDataIntegritySync uint8 = 1 << 3
	// Requests that reads be performed at the same level of integrety
	// requested for writes. This is similar to `O_RSYNC` in POSIX.
	//
	// The precise semantics of this operation have not yet been defined for
	// WASI. At this time, it should be interpreted as a request, and not a
	// requirement.
	DescriptorFlagsRequestedWriteSync uint8 = 1 << 4
	// Mutating directories mode: Directory contents may be mutated.
	//
	// When this flag is unset on a descriptor, operations using the
	// descriptor which would create, rename, delete, modify the data or
	// metadata of filesystem objects, or obtain another handle which
	// would permit any of those, shall fail with `error-code::read-only` if
	// they would otherwise succeed.
	//
	// This may only be set on directories.
	DescriptorFlagsMutateDirectory uint8 = 1 << 5
)

// Descriptor flags.
//
// Note: This was called `fdflags` in earlier versions of WASI.
type DescriptorFlags = uint8

const (
	// As long as the resolved path corresponds to a symbolic link, it is
	// expanded.
	PathFlagsSymlinkFollow uint8 = 1 << 0
)

// Flags determining the method of how paths are resolved.
type PathFlags = uint8

const (
	// Create file if it does not exist, similar to `O_CREAT` in POSIX.
	OpenFlagsCreate uint8 = 1 << 0
	// Fail if not a directory, similar to `O_DIRECTORY` in POSIX.
	OpenFlagsDirectory uint8 = 1 << 1
	// Fail if file already exists, similar to `O_EXCL` in POSIX.
	OpenFlagsExclusive uint8 = 1 << 2
	// Truncate file to size 0, similar to `O_TRUNC` in POSIX.
	OpenFlagsTruncate uint8 = 1 << 3
)

// Open flags used by `open-at`.
type OpenFlags = uint8

// Number of hard links to an inode.
type LinkCount = uint64

// File attributes.
//
// Note: This was called `filestat` in earlier versions of WASI.
type DescriptorStat struct {
	// File type.
	Type DescriptorType
	// Number of hard links to the file.
	LinkCount uint64
	// For regular files, the file size in bytes. For symbolic links, the
	// length in bytes of the pathname contained in the symbolic link.
	Size uint64
	// Last data access timestamp.
	//
	// If the `option` is none, the platform doesn't maintain an access
	// timestamp for this file.
	DataAccessTimestamp witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
	// Last data modification timestamp.
	//
	// If the `option` is none, the platform doesn't maintain a
	// modification timestamp for this file.
	DataModificationTimestamp witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
	// Last file status-change timestamp.
	//
	// If the `option` is none, the platform doesn't maintain a
	// status-change timestamp for this file.
	StatusChangeTimestamp witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
}

const (
	// Leave the timestamp set to its previous value.
	NewTimestampNoChange uint8 = 0
	// Set the timestamp to the current time of the system clock associated
	// with the filesystem.
	NewTimestampNow uint8 = 1
	// Set the timestamp to the given value.
	NewTimestampTimestamp uint8 = 2
)

// When setting a timestamp, this gives the value to set it to.
type NewTimestamp struct {
	tag   uint8
	value any
}

func (self NewTimestamp) Tag() uint8 {
	return self.tag
}

func (self NewTimestamp) Timestamp() wasi_clocks_0_2_0_wall_clock.Datetime {
	if self.tag != NewTimestampTimestamp {
		panic("tag mismatch")
	}
	return self.value.(wasi_clocks_0_2_0_wall_clock.Datetime)
}

func MakeNewTimestampNoChange() NewTimestamp {
	return NewTimestamp{NewTimestampNoChange, nil}
}
func MakeNewTimestampNow() NewTimestamp {
	return NewTimestamp{NewTimestampNow, nil}
}
func MakeNewTimestampTimestamp(value wasi_clocks_0_2_0_wall_clock.Datetime) NewTimestamp {
	return NewTimestamp{NewTimestampTimestamp, value}
}

// A directory entry.
type DirectoryEntry struct {
	// The type of the file referred to by this directory entry.
	Type DescriptorType
	// The name of the object.
	Name string
}

const (
	// Permission denied, similar to `EACCES` in POSIX.
	ErrorCodeAccess uint8 = 0
	// Resource unavailable, or operation would block, similar to `EAGAIN` and `EWOULDBLOCK` in POSIX.
	ErrorCodeWouldBlock uint8 = 1
	// Connection already in progress, similar to `EALREADY` in POSIX.
	ErrorCodeAlready uint8 = 2
	// Bad descriptor, similar to `EBADF` in POSIX.
	ErrorCodeBadDescriptor uint8 = 3
	// Device or resource busy, similar to `EBUSY` in POSIX.
	ErrorCodeBusy uint8 = 4
	// Resource deadlock would occur, similar to `EDEADLK` in POSIX.
	ErrorCodeDeadlock uint8 = 5
	// Storage quota exceeded, similar to `EDQUOT` in POSIX.
	ErrorCodeQuota uint8 = 6
	// File exists, similar to `EEXIST` in POSIX.
	ErrorCodeExist uint8 = 7
	// File too large, similar to `EFBIG` in POSIX.
	ErrorCodeFileTooLarge uint8 = 8
	// Illegal byte sequence, similar to `EILSEQ` in POSIX.
	ErrorCodeIllegalByteSequence uint8 = 9
	// Operation in progress, similar to `EINPROGRESS` in POSIX.
	ErrorCodeInProgress uint8 = 10
	// Interrupted function, similar to `EINTR` in POSIX.
	ErrorCodeInterrupted uint8 = 11
	// Invalid argument, similar to `EINVAL` in POSIX.
	ErrorCodeInvalid uint8 = 12
	// I/O error, similar to `EIO` in POSIX.
	ErrorCodeIo uint8 = 13
	// Is a directory, similar to `EISDIR` in POSIX.
	ErrorCodeIsDirectory uint8 = 14
	// Too many levels of symbolic links, similar to `ELOOP` in POSIX.
	ErrorCodeLoop uint8 = 15
	// Too many links, similar to `EMLINK` in POSIX.
	ErrorCodeTooManyLinks uint8 = 16
	// Message too large, similar to `EMSGSIZE` in POSIX.
	ErrorCodeMessageSize uint8 = 17
	// Filename too long, similar to `ENAMETOOLONG` in POSIX.
	ErrorCodeNameTooLong uint8 = 18
	// No such device, similar to `ENODEV` in POSIX.
	ErrorCodeNoDevice uint8 = 19
	// No such file or directory, similar to `ENOENT` in POSIX.
	ErrorCodeNoEntry uint8 = 20
	// No locks available, similar to `ENOLCK` in POSIX.
	ErrorCodeNoLock uint8 = 21
	// Not enough space, similar to `ENOMEM` in POSIX.
	ErrorCodeInsufficientMemory uint8 = 22
	// No space left on device, similar to `ENOSPC` in POSIX.
	ErrorCodeInsufficientSpace uint8 = 23
	// Not a directory or a symbolic link to a directory, similar to `ENOTDIR` in POSIX.
	ErrorCodeNotDirectory uint8 = 24
	// Directory not empty, similar to `ENOTEMPTY` in POSIX.
	ErrorCodeNotEmpty uint8 = 25
	// State not recoverable, similar to `ENOTRECOVERABLE` in POSIX.
	ErrorCodeNotRecoverable uint8 = 26
	// Not supported, similar to `ENOTSUP` and `ENOSYS` in POSIX.
	ErrorCodeUnsupported uint8 = 27
	// Inappropriate I/O control operation, similar to `ENOTTY` in POSIX.
	ErrorCodeNoTty uint8 = 28
	// No such device or address, similar to `ENXIO` in POSIX.
	ErrorCodeNoSuchDevice uint8 = 29
	// Value too large to be stored in data type, similar to `EOVERFLOW` in POSIX.
	ErrorCodeOverflow uint8 = 30
	// Operation not permitted, similar to `EPERM` in POSIX.
	ErrorCodeNotPermitted uint8 = 31
	// Broken pipe, similar to `EPIPE` in POSIX.
	ErrorCodePipe uint8 = 32
	// Read-only file system, similar to `EROFS` in POSIX.
	ErrorCodeReadOnly uint8 = 33
	// Invalid seek, similar to `ESPIPE` in POSIX.
	ErrorCodeInvalidSeek uint8 = 34
	// Text file busy, similar to `ETXTBSY` in POSIX.
	ErrorCodeTextFileBusy uint8 = 35
	// Cross-device link, similar to `EXDEV` in POSIX.
	ErrorCodeCrossDevice uint8 = 36
)

// Error codes returned by functions, similar to `errno` in POSIX.
// Not all of these error codes are returned by the functions provided by this
// API; some are used in higher-level library layers, and others are provided
// merely for alignment with POSIX.
type ErrorCode = uint8

const (
	// The application has no advice to give on its behavior with respect
	// to the specified data.
	AdviceNormal uint8 = 0
	// The application expects to access the specified data sequentially
	// from lower offsets to higher offsets.
	AdviceSequential uint8 = 1
	// The application expects to access the specified data in a random
	// order.
	AdviceRandom uint8 = 2
	// The application expects to access the specified data in the near
	// future.
	AdviceWillNeed uint8 = 3
	// The application expects that it will not access the specified data
	// in the near future.
	AdviceDontNeed uint8 = 4
	// The application expects to access the specified data once and then
	// not reuse it thereafter.
	AdviceNoReuse uint8 = 5
)

// File or memory access pattern advisory information.
type Advice = uint8

// A 128-bit hash value, split into parts because wasm doesn't have a
// 128-bit integer type.
type MetadataHashValue struct {
	// 64 bits of a 128-bit hash value.
	Lower uint64
	// Another 64 bits of a 128-bit hash value.
	Upper uint64
}

//go:wasmimport wasi:filesystem/types@0.2.0 [resource-drop]descriptor
func resourceDropDescriptor(handle int32)

// A descriptor is a reference to a filesystem object, which may be a file,
// directory, named pipe, special file, or other object on which filesystem
// calls may be made.
type Descriptor struct {
	handle *witRuntime.Handle
}

func (self *Descriptor) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Descriptor) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Descriptor) Handle() int32 {
	return self.handle.Use()
}

func (self *Descriptor) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropDescriptor(handle)
	}
}

func DescriptorFromOwnHandle(handleValue int32) *Descriptor {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Descriptor{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropDescriptor(handleValue)
		}
	}, 0)
	return value
}

func DescriptorFromBorrowHandle(handleValue int32) *Descriptor {
	handle := witRuntime.MakeHandle(handleValue)
	return &Descriptor{handle}
}

//go:wasmimport wasi:filesystem/types@0.2.0 [resource-drop]directory-entry-stream
func resourceDropDirectoryEntryStream(handle int32)

// A stream of directory entries.
type DirectoryEntryStream struct {
	handle *witRuntime.Handle
}

func (self *DirectoryEntryStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *DirectoryEntryStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *DirectoryEntryStream) Handle() int32 {
	return self.handle.Use()
}

func (self *DirectoryEntryStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropDirectoryEntryStream(handle)
	}
}

func DirectoryEntryStreamFromOwnHandle(handleValue int32) *DirectoryEntryStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &DirectoryEntryStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropDirectoryEntryStream(handleValue)
		}
	}, 0)
	return value
}

func DirectoryEntryStreamFromBorrowHandle(handleValue int32) *DirectoryEntryStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &DirectoryEntryStream{handle}
}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.read-via-stream
func wasm_import_method_descriptor_read_via_stream(arg0 int32, arg1 int64, arg2 uintptr)

func (self *Descriptor) ReadViaStream(offset uint64) witTypes.Result[*wasi_io_0_2_0_streams.InputStream, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_descriptor_read_via_stream((self).Handle(), int64(offset), returnArea)
	var result witTypes.Result[*wasi_io_0_2_0_streams.InputStream, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasi_io_0_2_0_streams.InputStream, ErrorCode](wasi_io_0_2_0_streams.InputStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*wasi_io_0_2_0_streams.InputStream, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.write-via-stream
func wasm_import_method_descriptor_write_via_stream(arg0 int32, arg1 int64, arg2 uintptr)

func (self *Descriptor) WriteViaStream(offset uint64) witTypes.Result[*wasi_io_0_2_0_streams.OutputStream, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_descriptor_write_via_stream((self).Handle(), int64(offset), returnArea)
	var result witTypes.Result[*wasi_io_0_2_0_streams.OutputStream, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasi_io_0_2_0_streams.OutputStream, ErrorCode](wasi_io_0_2_0_streams.OutputStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*wasi_io_0_2_0_streams.OutputStream, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.append-via-stream
func wasm_import_method_descriptor_append_via_stream(arg0 int32, arg1 uintptr)

func (self *Descriptor) AppendViaStream() witTypes.Result[*wasi_io_0_2_0_streams.OutputStream, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_descriptor_append_via_stream((self).Handle(), returnArea)
	var result witTypes.Result[*wasi_io_0_2_0_streams.OutputStream, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasi_io_0_2_0_streams.OutputStream, ErrorCode](wasi_io_0_2_0_streams.OutputStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*wasi_io_0_2_0_streams.OutputStream, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.advise
func wasm_import_method_descriptor_advise(arg0 int32, arg1 int64, arg2 int64, arg3 int32, arg4 uintptr)

func (self *Descriptor) Advise(offset uint64, length uint64, advice Advice) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_advise((self).Handle(), int64(offset), int64(length), int32(advice), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.sync-data
func wasm_import_method_descriptor_sync_data(arg0 int32, arg1 uintptr)

func (self *Descriptor) SyncData() witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_sync_data((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.get-flags
func wasm_import_method_descriptor_get_flags(arg0 int32, arg1 uintptr)

func (self *Descriptor) GetFlags() witTypes.Result[DescriptorFlags, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_get_flags((self).Handle(), returnArea)
	var result witTypes.Result[DescriptorFlags, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[DescriptorFlags, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	case 1:

		result = witTypes.Err[DescriptorFlags, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.get-type
func wasm_import_method_descriptor_get_type(arg0 int32, arg1 uintptr)

func (self *Descriptor) GetType() witTypes.Result[DescriptorType, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_get_type((self).Handle(), returnArea)
	var result witTypes.Result[DescriptorType, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[DescriptorType, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	case 1:

		result = witTypes.Err[DescriptorType, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.set-size
func wasm_import_method_descriptor_set_size(arg0 int32, arg1 int64, arg2 uintptr)

func (self *Descriptor) SetSize(size uint64) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_set_size((self).Handle(), int64(size), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.set-times
func wasm_import_method_descriptor_set_times(arg0 int32, arg1 int32, arg2 int64, arg3 int32, arg4 int32, arg5 int64, arg6 int32, arg7 uintptr)

func (self *Descriptor) SetTimes(dataAccessTimestamp NewTimestamp, dataModificationTimestamp NewTimestamp) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	var variant int32
	var variant0 int64
	var variant1 int32
	switch dataAccessTimestamp.Tag() {
	case NewTimestampNoChange:

		variant = int32(0)
		variant0 = 0
		variant1 = 0

	case NewTimestampNow:

		variant = int32(1)
		variant0 = 0
		variant1 = 0

	case NewTimestampTimestamp:
		payload := dataAccessTimestamp.Timestamp()

		variant = int32(2)
		variant0 = int64((payload).Seconds)
		variant1 = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}
	var variant2 int32
	var variant3 int64
	var variant4 int32
	switch dataModificationTimestamp.Tag() {
	case NewTimestampNoChange:

		variant2 = int32(0)
		variant3 = 0
		variant4 = 0

	case NewTimestampNow:

		variant2 = int32(1)
		variant3 = 0
		variant4 = 0

	case NewTimestampTimestamp:
		payload := dataModificationTimestamp.Timestamp()

		variant2 = int32(2)
		variant3 = int64((payload).Seconds)
		variant4 = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}
	wasm_import_method_descriptor_set_times((self).Handle(), variant, variant0, variant1, variant2, variant3, variant4, returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result5 := result
	return result5

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.read
func wasm_import_method_descriptor_read(arg0 int32, arg1 int64, arg2 int64, arg3 uintptr)

func (self *Descriptor) Read(length uint64, offset uint64) witTypes.Result[witTypes.Tuple2[[]uint8, bool], ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	wasm_import_method_descriptor_read((self).Handle(), int64(length), int64(offset), returnArea)
	var result witTypes.Result[witTypes.Tuple2[[]uint8, bool], ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[witTypes.Tuple2[[]uint8, bool], ErrorCode](witTypes.Tuple2[[]uint8, bool]{value, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))) != 0)})
	case 1:

		result = witTypes.Err[witTypes.Tuple2[[]uint8, bool], ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.write
func wasm_import_method_descriptor_write(arg0 int32, arg1 uintptr, arg2 uint32, arg3 int64, arg4 uintptr)

func (self *Descriptor) Write(buffer []uint8, offset uint64) witTypes.Result[uint64, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	data := unsafe.Pointer(unsafe.SliceData(buffer))
	pinner.Pin(data)
	wasm_import_method_descriptor_write((self).Handle(), uintptr(data), uint32(len(buffer)), int64(offset), returnArea)
	var result witTypes.Result[uint64, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, ErrorCode](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:

		result = witTypes.Err[uint64, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.read-directory
func wasm_import_method_descriptor_read_directory(arg0 int32, arg1 uintptr)

func (self *Descriptor) ReadDirectory() witTypes.Result[*DirectoryEntryStream, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_descriptor_read_directory((self).Handle(), returnArea)
	var result witTypes.Result[*DirectoryEntryStream, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*DirectoryEntryStream, ErrorCode](DirectoryEntryStreamFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*DirectoryEntryStream, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.sync
func wasm_import_method_descriptor_sync(arg0 int32, arg1 uintptr)

func (self *Descriptor) Sync() witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_method_descriptor_sync((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.create-directory-at
func wasm_import_method_descriptor_create_directory_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Descriptor) CreateDirectoryAt(path string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_create_directory_at((self).Handle(), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.stat
func wasm_import_method_descriptor_stat(arg0 int32, arg1 uintptr)

func (self *Descriptor) Stat() witTypes.Result[DescriptorStat, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 104, 8))
	wasm_import_method_descriptor_stat((self).Handle(), returnArea)
	var result witTypes.Result[DescriptorStat, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 32))) {
		case 0:

			option = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 40))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 48)))})
		default:
			panic("unreachable")
		}
		var option0 witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 56))) {
		case 0:

			option0 = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option0 = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 64))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 72)))})
		default:
			panic("unreachable")
		}
		var option1 witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 80))) {
		case 0:

			option1 = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option1 = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 88))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 96)))})
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[DescriptorStat, ErrorCode](DescriptorStat{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24))), option, option0, option1})
	case 1:

		result = witTypes.Err[DescriptorStat, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result2 := result
	return result2

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.stat-at
func wasm_import_method_descriptor_stat_at(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func (self *Descriptor) StatAt(pathFlags PathFlags, path string) witTypes.Result[DescriptorStat, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 104, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_stat_at((self).Handle(), int32(pathFlags), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[DescriptorStat, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 32))) {
		case 0:

			option = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 40))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 48)))})
		default:
			panic("unreachable")
		}
		var option0 witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 56))) {
		case 0:

			option0 = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option0 = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 64))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 72)))})
		default:
			panic("unreachable")
		}
		var option1 witTypes.Option[wasi_clocks_0_2_0_wall_clock.Datetime]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 80))) {
		case 0:

			option1 = witTypes.None[wasi_clocks_0_2_0_wall_clock.Datetime]()
		case 1:

			option1 = witTypes.Some[wasi_clocks_0_2_0_wall_clock.Datetime](wasi_clocks_0_2_0_wall_clock.Datetime{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 88))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 96)))})
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[DescriptorStat, ErrorCode](DescriptorStat{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24))), option, option0, option1})
	case 1:

		result = witTypes.Err[DescriptorStat, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result2 := result
	return result2

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.set-times-at
func wasm_import_method_descriptor_set_times_at(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 int64, arg6 int32, arg7 int32, arg8 int64, arg9 int32, arg10 uintptr)

func (self *Descriptor) SetTimesAt(pathFlags PathFlags, path string, dataAccessTimestamp NewTimestamp, dataModificationTimestamp NewTimestamp) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	var variant int32
	var variant0 int64
	var variant1 int32
	switch dataAccessTimestamp.Tag() {
	case NewTimestampNoChange:

		variant = int32(0)
		variant0 = 0
		variant1 = 0

	case NewTimestampNow:

		variant = int32(1)
		variant0 = 0
		variant1 = 0

	case NewTimestampTimestamp:
		payload := dataAccessTimestamp.Timestamp()

		variant = int32(2)
		variant0 = int64((payload).Seconds)
		variant1 = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}
	var variant2 int32
	var variant3 int64
	var variant4 int32
	switch dataModificationTimestamp.Tag() {
	case NewTimestampNoChange:

		variant2 = int32(0)
		variant3 = 0
		variant4 = 0

	case NewTimestampNow:

		variant2 = int32(1)
		variant3 = 0
		variant4 = 0

	case NewTimestampTimestamp:
		payload := dataModificationTimestamp.Timestamp()

		variant2 = int32(2)
		variant3 = int64((payload).Seconds)
		variant4 = int32((payload).Nanoseconds)

	default:
		panic("unreachable")
	}
	wasm_import_method_descriptor_set_times_at((self).Handle(), int32(pathFlags), uintptr(utf8), uint32(len(path)), variant, variant0, variant1, variant2, variant3, variant4, returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result5 := result
	return result5

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.link-at
func wasm_import_method_descriptor_link_at(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 uintptr, arg6 uint32, arg7 uintptr)

func (self *Descriptor) LinkAt(oldPathFlags PathFlags, oldPath string, newDescriptor *Descriptor, newPath string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(oldPath))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(newPath))
	pinner.Pin(utf80)
	wasm_import_method_descriptor_link_at((self).Handle(), int32(oldPathFlags), uintptr(utf8), uint32(len(oldPath)), (newDescriptor).Handle(), uintptr(utf80), uint32(len(newPath)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.open-at
func wasm_import_method_descriptor_open_at(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 int32, arg5 int32, arg6 uintptr)

func (self *Descriptor) OpenAt(pathFlags PathFlags, path string, openFlags OpenFlags, flags DescriptorFlags) witTypes.Result[*Descriptor, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_open_at((self).Handle(), int32(pathFlags), uintptr(utf8), uint32(len(path)), int32(openFlags), int32(flags), returnArea)
	var result witTypes.Result[*Descriptor, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Descriptor, ErrorCode](DescriptorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*Descriptor, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.readlink-at
func wasm_import_method_descriptor_readlink_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Descriptor) ReadlinkAt(path string) witTypes.Result[string, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_readlink_at((self).Handle(), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[string, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[string, ErrorCode](value)
	case 1:

		result = witTypes.Err[string, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.remove-directory-at
func wasm_import_method_descriptor_remove_directory_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Descriptor) RemoveDirectoryAt(path string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_remove_directory_at((self).Handle(), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.rename-at
func wasm_import_method_descriptor_rename_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 int32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func (self *Descriptor) RenameAt(oldPath string, newDescriptor *Descriptor, newPath string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(oldPath))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(newPath))
	pinner.Pin(utf80)
	wasm_import_method_descriptor_rename_at((self).Handle(), uintptr(utf8), uint32(len(oldPath)), (newDescriptor).Handle(), uintptr(utf80), uint32(len(newPath)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.symlink-at
func wasm_import_method_descriptor_symlink_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Descriptor) SymlinkAt(oldPath string, newPath string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(oldPath))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(newPath))
	pinner.Pin(utf80)
	wasm_import_method_descriptor_symlink_at((self).Handle(), uintptr(utf8), uint32(len(oldPath)), uintptr(utf80), uint32(len(newPath)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.unlink-file-at
func wasm_import_method_descriptor_unlink_file_at(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Descriptor) UnlinkFileAt(path string) witTypes.Result[witTypes.Unit, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_unlink_file_at((self).Handle(), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[witTypes.Unit, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.is-same-object
func wasm_import_method_descriptor_is_same_object(arg0 int32, arg1 int32) int32

func (self *Descriptor) IsSameObject(other *Descriptor) bool {

	result := wasm_import_method_descriptor_is_same_object((self).Handle(), (other).Handle())
	return (result != 0)

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.metadata-hash
func wasm_import_method_descriptor_metadata_hash(arg0 int32, arg1 uintptr)

func (self *Descriptor) MetadataHash() witTypes.Result[MetadataHashValue, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 24, 8))
	wasm_import_method_descriptor_metadata_hash((self).Handle(), returnArea)
	var result witTypes.Result[MetadataHashValue, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[MetadataHashValue, ErrorCode](MetadataHashValue{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16)))})
	case 1:

		result = witTypes.Err[MetadataHashValue, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]descriptor.metadata-hash-at
func wasm_import_method_descriptor_metadata_hash_at(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func (self *Descriptor) MetadataHashAt(pathFlags PathFlags, path string) witTypes.Result[MetadataHashValue, ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 24, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(path))
	pinner.Pin(utf8)
	wasm_import_method_descriptor_metadata_hash_at((self).Handle(), int32(pathFlags), uintptr(utf8), uint32(len(path)), returnArea)
	var result witTypes.Result[MetadataHashValue, ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[MetadataHashValue, ErrorCode](MetadataHashValue{uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))), uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16)))})
	case 1:

		result = witTypes.Err[MetadataHashValue, ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 [method]directory-entry-stream.read-directory-entry
func wasm_import_method_directory_entry_stream_read_directory_entry(arg0 int32, arg1 uintptr)

func (self *DirectoryEntryStream) ReadDirectoryEntry() witTypes.Result[witTypes.Option[DirectoryEntry], ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	wasm_import_method_directory_entry_stream_read_directory_entry((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Option[DirectoryEntry], ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[DirectoryEntry]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = witTypes.None[DirectoryEntry]()
		case 1:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))

			option = witTypes.Some[DirectoryEntry](DirectoryEntry{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))), value})
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[DirectoryEntry], ErrorCode](option)
	case 1:

		result = witTypes.Err[witTypes.Option[DirectoryEntry], ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:filesystem/types@0.2.0 filesystem-error-code
func wasm_import_filesystem_error_code(arg0 int32, arg1 uintptr)

func FilesystemErrorCode(err *wasi_io_0_2_0_error.Error) witTypes.Option[ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	wasm_import_filesystem_error_code((err).Handle(), returnArea)
	var option witTypes.Option[ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[ErrorCode]()
	case 1:

		option = witTypes.Some[ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
