spin_manifest_version = 2

[application]
name = "go-redis-outbound-async-raw-example"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@akamai.com>"]
description = "Using Spin with Redis via asynchronous bindings"

[[trigger.http]]
route = "/"
component = "redis-outbound"

[component.redis-outbound]
source = "main.wasm"
environment = { REDIS_ADDRESS = "redis://localhost:6379", REDIS_CHANNEL = "messages" }
allowed_outbound_hosts = ["redis://localhost:6379"]

[component.redis-outbound.build]
command = "go tool componentize-go -w wasi:http/service@0.3.0-rc-2026-03-15 -w platform build"
watch = ["**/*.go", "go.mod"]
