// Code generated by wit-bindgen-go. DO NOT EDIT.

package store

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:keyvalue@0.2.0-draft2".

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [resource-drop]bucket
//go:noescape
func wasmimport_BucketResourceDrop(self0 uint32)

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.delete
//go:noescape
func wasmimport_BucketDelete(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.exists
//go:noescape
func wasmimport_BucketExists(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, bool, Error])

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.get
//go:noescape
func wasmimport_BucketGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], Error])

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.list-keys
//go:noescape
func wasmimport_BucketListKeys(self0 uint32, cursor0 uint32, cursor1 *uint8, cursor2 uint32, result *cm.Result[KeyResponseShape, KeyResponse, Error])

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.set
//go:noescape
func wasmimport_BucketSet(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 open
//go:noescape
func wasmimport_Open(identifier0 *uint8, identifier1 uint32, result *cm.Result[ErrorShape, Bucket, Error])
