// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package fermyon_spin_redis

import (
	"github.com/spinframework/spin-go-sdk/v3/internal/fermyon_spin_redis_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Payload = []uint8
type RedisParameter = fermyon_spin_redis_types.RedisParameter
type RedisResult = fermyon_spin_redis_types.RedisResult
type Error = fermyon_spin_redis_types.Error

//go:wasmimport fermyon:spin/redis publish
func wasm_import_publish(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Publish(address string, channel string, payload []uint8) witTypes.Result[witTypes.Unit, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(channel))
	pinner.Pin(utf80)
	data := unsafe.Pointer(unsafe.SliceData(payload))
	pinner.Pin(data)
	wasm_import_publish(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(channel)), uintptr(data), uint32(len(payload)), returnArea)
	var result witTypes.Result[witTypes.Unit, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, fermyon_spin_redis_types.Error](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis get
func wasm_import_get(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func Get(address string, key string) witTypes.Result[[]uint8, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	wasm_import_get(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), returnArea)
	var result witTypes.Result[[]uint8, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, fermyon_spin_redis_types.Error](value)
	case 1:

		result = witTypes.Err[[]uint8, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis set
func wasm_import_set(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Set(address string, key string, value []uint8) witTypes.Result[witTypes.Unit, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 2, 1))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_set(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result witTypes.Result[witTypes.Unit, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, fermyon_spin_redis_types.Error](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 1)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis incr
func wasm_import_incr(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func Incr(address string, key string) witTypes.Result[int64, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	wasm_import_incr(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), returnArea)
	var result witTypes.Result[int64, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[int64, fermyon_spin_redis_types.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:

		result = witTypes.Err[int64, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis del
func wasm_import_del(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func Del(address string, keys []string) witTypes.Result[int64, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	slice := keys
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf80 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))

	}

	wasm_import_del(uintptr(utf8), uint32(len(address)), uintptr(result), length, returnArea)
	var result1 witTypes.Result[int64, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result1 = witTypes.Ok[int64, fermyon_spin_redis_types.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:

		result1 = witTypes.Err[int64, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/redis sadd
func wasm_import_sadd(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Sadd(address string, key string, values []string) witTypes.Result[int64, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	slice := values
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf81 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf81)))

	}

	wasm_import_sadd(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), uintptr(result), length, returnArea)
	var result2 witTypes.Result[int64, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result2 = witTypes.Ok[int64, fermyon_spin_redis_types.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:

		result2 = witTypes.Err[int64, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result3 := result2
	return result3

}

//go:wasmimport fermyon:spin/redis smembers
func wasm_import_smembers(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func Smembers(address string, key string) witTypes.Result[[]string, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	wasm_import_smembers(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), returnArea)
	var result1 witTypes.Result[[]string, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result1 = witTypes.Ok[[]string, fermyon_spin_redis_types.Error](result)
	case 1:

		result1 = witTypes.Err[[]string, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/redis srem
func wasm_import_srem(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Srem(address string, key string, values []string) witTypes.Result[int64, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf80)
	slice := values
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf81 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf81)))

	}

	wasm_import_srem(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(key)), uintptr(result), length, returnArea)
	var result2 witTypes.Result[int64, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result2 = witTypes.Ok[int64, fermyon_spin_redis_types.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:

		result2 = witTypes.Err[int64, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))))
	default:
		panic("unreachable")
	}
	result3 := result2
	return result3

}

//go:wasmimport fermyon:spin/redis execute
func wasm_import_execute(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Execute(address string, command string, arguments []fermyon_spin_redis_types.RedisParameter) witTypes.Result[[]fermyon_spin_redis_types.RedisResult, fermyon_spin_redis_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(command))
	pinner.Pin(utf80)
	slice := arguments
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+2*4))

		switch element.Tag() {
		case fermyon_spin_redis_types.RedisParameterInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_redis_types.RedisParameterBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		default:
			panic("unreachable")
		}

	}

	wasm_import_execute(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(command)), uintptr(result), length, returnArea)
	var result3 witTypes.Result[[]fermyon_spin_redis_types.RedisResult, fermyon_spin_redis_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result2 := make([]fermyon_spin_redis_types.RedisResult, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(8+2*4))
			var variant fermyon_spin_redis_types.RedisResult
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				variant = fermyon_spin_redis_types.MakeRedisResultNil()

			case 1:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant = fermyon_spin_redis_types.MakeRedisResultStatus(value)

			case 2:

				variant = fermyon_spin_redis_types.MakeRedisResultInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 3:
				value1 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant = fermyon_spin_redis_types.MakeRedisResultBinary(value1)

			default:
				panic("unreachable")
			}

			result2 = append(result2, variant)
		}

		result3 = witTypes.Ok[[]fermyon_spin_redis_types.RedisResult, fermyon_spin_redis_types.Error](result2)
	case 1:

		result3 = witTypes.Err[[]fermyon_spin_redis_types.RedisResult, fermyon_spin_redis_types.Error](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result4 := result3
	return result4

}
