// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package httptrigger represents the world "fermyon:spin/http-trigger@3.0.0".
//
// The full world of a guest targeting an http-trigger
package httptrigger
