// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_clocks_0_2_6_monotonic_clock

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_io_0_2_6_poll"
)

type Pollable = wasi_io_0_2_6_poll.Pollable

// An instant in time, in nanoseconds. An instant is relative to an
// unspecified initial value, and can only be compared to instances from
// the same monotonic-clock.
type Instant = uint64

// A duration of time, in nanoseconds.
type Duration = uint64

//go:wasmimport wasi:clocks/monotonic-clock@0.2.6 now
func wasm_import_now() int64

func Now() uint64 {

	result := wasm_import_now()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.6 resolution
func wasm_import_resolution() int64

func Resolution() uint64 {

	result := wasm_import_resolution()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.6 subscribe-instant
func wasm_import_subscribe_instant(arg0 int64) int32

func SubscribeInstant(when uint64) *wasi_io_0_2_6_poll.Pollable {

	result := wasm_import_subscribe_instant(int64(when))
	return wasi_io_0_2_6_poll.PollableFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport wasi:clocks/monotonic-clock@0.2.6 subscribe-duration
func wasm_import_subscribe_duration(arg0 int64) int32

func SubscribeDuration(when uint64) *wasi_io_0_2_6_poll.Pollable {

	result := wasm_import_subscribe_duration(int64(when))
	return wasi_io_0_2_6_poll.PollableFromOwnHandle(int32(uintptr(result)))

}
