// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package spin_sqlite_3_1_0_sqlite

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport spin:sqlite/sqlite@3.1.0 [stream-new-0][method]connection.execute-async
func wasm_stream_new_row_result() uint64

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][stream-read-0][method]connection.execute-async
func wasm_stream_read_row_result(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][stream-write-0][method]connection.execute-async
func wasm_stream_write_row_result(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:sqlite/sqlite@3.1.0 [stream-drop-readable-0][method]connection.execute-async
func wasm_stream_drop_readable_row_result(handle int32)

//go:wasmimport spin:sqlite/sqlite@3.1.0 [stream-drop-writable-0][method]connection.execute-async
func wasm_stream_drop_writable_row_result(handle int32)

func wasm_stream_lift_row_result(src unsafe.Pointer) RowResult {
	result := make([]Value, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(src), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0)))), index*(8+2*4))
		var variant Value
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:

			variant = MakeValueInteger(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 1:

			variant = MakeValueReal(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

			variant = MakeValueText(value)

		case 3:
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

			variant = MakeValueBlob(value0)

		case 4:

			variant = MakeValueNull()

		default:
			panic("unreachable")
		}

		result = append(result, variant)
	}

	return RowResult{result}
}

func wasm_stream_lower_row_result(
	pinner *runtime.Pinner,
	value RowResult,
	dst unsafe.Pointer,
) func() {
	slice := (value).Values
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*(8+2*4))

		switch element.Tag() {
		case ValueInteger:
			payload := element.Integer()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueReal:
			payload := element.Real()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8)))

		case ValueBlob:
			payload := element.Blob()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ValueNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 0)) = uint32(uintptr(uintptr(result1)))

	return func() {}
}

var wasm_stream_vtable_row_result = witTypes.StreamVtable[RowResult]{
	(2 * 4),
	4,
	wasm_stream_read_row_result,
	wasm_stream_write_row_result,
	nil,
	nil,
	wasm_stream_drop_readable_row_result,
	wasm_stream_drop_writable_row_result,
	wasm_stream_lift_row_result,
	wasm_stream_lower_row_result,
}

func MakeStreamRowResult() (*witTypes.StreamWriter[RowResult], *witTypes.StreamReader[RowResult]) {
	pair := wasm_stream_new_row_result()
	return witTypes.MakeStreamWriter[RowResult](&wasm_stream_vtable_row_result, int32(pair>>32)),
		witTypes.MakeStreamReader[RowResult](&wasm_stream_vtable_row_result, int32(pair&0xFFFFFFFF))
}

func LiftStreamRowResult(handle int32) *witTypes.StreamReader[RowResult] {
	return witTypes.MakeStreamReader[RowResult](&wasm_stream_vtable_row_result, handle)
}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [future-new-1][method]connection.execute-async
func wasm_future_new_result_unit_error() uint64

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][future-read-1][method]connection.execute-async
func wasm_future_read_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][future-write-1][method]connection.execute-async
func wasm_future_write_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:sqlite/sqlite@3.1.0 [future-drop-readable-1][method]connection.execute-async
func wasm_future_drop_readable_result_unit_error(handle int32)

//go:wasmimport spin:sqlite/sqlite@3.1.0 [future-drop-writable-1][method]connection.execute-async
func wasm_future_drop_writable_result_unit_error(handle int32)

func wasm_future_lift_result_unit_error(src unsafe.Pointer) witTypes.Result[witTypes.Unit, Error] {
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 4))) {
		case 0:

			variant = MakeErrorNoSuchDatabase()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidConnection()

		case 3:

			variant = MakeErrorDatabaseFull()

		case 4:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_error(
	pinner *runtime.Pinner,
	value witTypes.Result[witTypes.Unit, Error],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))

		switch payload.Tag() {
		case ErrorNoSuchDatabase:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(0))

		case ErrorAccessDenied:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(1))

		case ErrorInvalidConnection:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(2))

		case ErrorDatabaseFull:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(3))

		case ErrorIo:
			payload := payload.Io()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(4))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_error = witTypes.FutureVtable[witTypes.Result[witTypes.Unit, Error]]{
	(4 * 4),
	4,
	wasm_future_read_result_unit_error,
	wasm_future_write_result_unit_error,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_error,
	wasm_future_drop_writable_result_unit_error,
	wasm_future_lift_result_unit_error,
	wasm_future_lower_result_unit_error,
}

func MakeFutureResultUnitError() (*witTypes.FutureWriter[witTypes.Result[witTypes.Unit, Error]], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]) {
	pair := wasm_future_new_result_unit_error()
	return witTypes.MakeFutureWriter[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair>>32)),
		witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitError(handle int32) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]] {
	return witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, handle)
}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A handle to an open sqlite instance
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

const (
	// The host does not recognize the database name requested.
	ErrorNoSuchDatabase uint8 = 0
	// The requesting component does not have access to the specified database (which may or may not exist).
	ErrorAccessDenied uint8 = 1
	// The provided connection is not valid
	ErrorInvalidConnection uint8 = 2
	// The database has reached its capacity
	ErrorDatabaseFull uint8 = 3
	// Some implementation-specific error has occurred (e.g. I/O)
	ErrorIo uint8 = 4
)

// The set of errors which may be raised by functions in this interface
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Io() string {
	if self.tag != ErrorIo {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorNoSuchDatabase() Error {
	return Error{ErrorNoSuchDatabase, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorInvalidConnection() Error {
	return Error{ErrorInvalidConnection, nil}
}
func MakeErrorDatabaseFull() Error {
	return Error{ErrorDatabaseFull, nil}
}
func MakeErrorIo(value string) Error {
	return Error{ErrorIo, value}
}

const (
	ValueInteger uint8 = 0
	ValueReal    uint8 = 1
	ValueText    uint8 = 2
	ValueBlob    uint8 = 3
	ValueNull    uint8 = 4
)

// A single column's result from a database query
type Value struct {
	tag   uint8
	value any
}

func (self Value) Tag() uint8 {
	return self.tag
}

func (self Value) Integer() int64 {
	if self.tag != ValueInteger {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self Value) Real() float64 {
	if self.tag != ValueReal {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self Value) Text() string {
	if self.tag != ValueText {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Value) Blob() []uint8 {
	if self.tag != ValueBlob {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeValueInteger(value int64) Value {
	return Value{ValueInteger, value}
}
func MakeValueReal(value float64) Value {
	return Value{ValueReal, value}
}
func MakeValueText(value string) Value {
	return Value{ValueText, value}
}
func MakeValueBlob(value []uint8) Value {
	return Value{ValueBlob, value}
}
func MakeValueNull() Value {
	return Value{ValueNull, nil}
}

// A set of values for each of the columns in a query-result
type RowResult struct {
	Values []Value
}

// A result of a query
type QueryResult struct {
	// The names of the columns retrieved in the query
	Columns []string
	// the row results each containing the values for all the columns for a given row
	Rows []RowResult
}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func ConnectionOpen(database string) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(database))
	pinner.Pin(utf8)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(database)), returnArea)
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchDatabase()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidConnection()

		case 3:

			variant = MakeErrorDatabaseFull()

		case 4:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][static]connection.open-async
func wasm_import_static_connection_open_async(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func ConnectionOpenAsync(database string) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(database))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_static_connection_open_async(uintptr(utf8), uint32(len(database)), returnArea)))
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchDatabase()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidConnection()

		case 3:

			variant = MakeErrorDatabaseFull()

		case 4:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Execute(statement string, parameters []Value) witTypes.Result[QueryResult, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := parameters
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+2*4))

		switch element.Tag() {
		case ValueInteger:
			payload := element.Integer()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueReal:
			payload := element.Real()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case ValueBlob:
			payload := element.Blob()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ValueNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result), length, returnArea)
	var result8 witTypes.Result[QueryResult, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result1 = append(result1, value)
		}

		result5 := make([]RowResult, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(2*4))
			result4 := make([]Value, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*(8+2*4))
				var variant Value
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
				case 0:

					variant = MakeValueInteger(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 1:

					variant = MakeValueReal(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 2:
					value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeValueText(value2)

				case 3:
					value3 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeValueBlob(value3)

				case 4:

					variant = MakeValueNull()

				default:
					panic("unreachable")
				}

				result4 = append(result4, variant)
			}

			result5 = append(result5, RowResult{result4})
		}

		result8 = witTypes.Ok[QueryResult, Error](QueryResult{result1, result5})
	case 1:
		var variant7 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant7 = MakeErrorNoSuchDatabase()

		case 1:

			variant7 = MakeErrorAccessDenied()

		case 2:

			variant7 = MakeErrorInvalidConnection()

		case 3:

			variant7 = MakeErrorDatabaseFull()

		case 4:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorIo(value6)

		default:
			panic("unreachable")
		}

		result8 = witTypes.Err[QueryResult, Error](variant7)
	default:
		panic("unreachable")
	}
	result9 := result8
	return result9

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][method]connection.execute-async
func wasm_import_method_connection_execute_async(arg0 uintptr, arg1 uintptr) int32

func (self *Connection) ExecuteAsync(statement string, parameters []Value) witTypes.Result[witTypes.Tuple3[[]string, *witTypes.StreamReader[RowResult], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 + 3*4), 4))
	params := witRuntime.Allocate(pinner, (5 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len(statement)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	slice := parameters
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+2*4))

		switch element.Tag() {
		case ValueInteger:
			payload := element.Integer()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueReal:
			payload := element.Real()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case ValueBlob:
			payload := element.Blob()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ValueNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 0)) = uint32(uintptr(uintptr(result)))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_execute_async(uintptr(params), returnArea)))
	var result3 witTypes.Result[witTypes.Tuple3[[]string, *witTypes.StreamReader[RowResult], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result1 = append(result1, value)
		}

		result3 = witTypes.Ok[witTypes.Tuple3[[]string, *witTypes.StreamReader[RowResult], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error](witTypes.Tuple3[[]string, *witTypes.StreamReader[RowResult], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]]{result1, LiftStreamRowResult(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))), LiftFutureResultUnitError(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 3*4))))})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchDatabase()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidConnection()

		case 3:

			variant = MakeErrorDatabaseFull()

		case 4:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value2)

		default:
			panic("unreachable")
		}

		result3 = witTypes.Err[witTypes.Tuple3[[]string, *witTypes.StreamReader[RowResult], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error](variant)
	default:
		panic("unreachable")
	}

	return result3

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [method]connection.last-insert-rowid
func wasm_import_method_connection_last_insert_rowid(arg0 int32) int64

func (self *Connection) LastInsertRowid() int64 {

	result := wasm_import_method_connection_last_insert_rowid((self).Handle())
	return result

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][method]connection.last-insert-rowid-async
func wasm_import_method_connection_last_insert_rowid_async(arg0 int32, arg1 uintptr) int32

func (self *Connection) LastInsertRowidAsync() int64 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_last_insert_rowid_async((self).Handle(), returnArea)))

	return *(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 0))

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [method]connection.changes
func wasm_import_method_connection_changes(arg0 int32) int64

func (self *Connection) Changes() uint64 {

	result := wasm_import_method_connection_changes((self).Handle())
	return uint64(result)

}

//go:wasmimport spin:sqlite/sqlite@3.1.0 [async-lower][method]connection.changes-async
func wasm_import_method_connection_changes_async(arg0 int32, arg1 uintptr) int32

func (self *Connection) ChangesAsync() uint64 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 8))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_changes_async((self).Handle(), returnArea)))

	return uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 0)))

}
