// Package llm provides access to Large Language Model inferencing and embeddings
// within Spin components.
package llm

import (
	"fmt"

	llm "github.com/spinframework/spin-go-sdk/v3/imports/fermyon_spin_2_0_0_llm"
	wit "go.bytecodealliance.org/pkg/wit/types"
)

const (
	// Llama2Chat is the Llama 2 Chat model for inferencing.
	Llama2Chat InferencingModel = "llama2-chat"
	// CodellamaInstruct is the Code Llama Instruct model for inferencing.
	CodellamaInstruct InferencingModel = "codellama-instruct"
)

// InferencingParams configures the parameters for an inferencing request.
type InferencingParams struct {
	// The maximum tokens that should be inferred.
	//
	// Note: the backing implementation may return less tokens.
	MaxTokens uint32 `json:"max-tokens"`

	// The amount the model should avoid repeating tokens.
	RepeatPenalty float32 `json:"repeat-penalty"`

	// The number of tokens the model should apply the repeat penalty to.
	RepeatPenaltyLastNTokenCount uint32 `json:"repeat-penalty-last-n-token-count"`

	// The randomness with which the next token is selected.
	Temperature float32 `json:"temperature"`

	// The number of possible next tokens the model will choose from.
	TopK uint32 `json:"top-k"`

	// The probability total of next tokens the model will choose from.
	TopP float32 `json:"top-p"`
}

// InferencingResult represents the result of an inferencing request.
type InferencingResult struct {
	// The text generated by the model
	// TODO: this should be a stream
	Text string `json:"text"`

	// Usage information about the inferencing request
	Usage InferencingUsage `json:"usage"`
}

// InferencingUsage contains usage information related to the inferencing result.
type InferencingUsage struct {
	// Number of tokens in the prompt
	PromptTokenCount uint32 `json:"prompt-token-count"`

	// Number of tokens generated by the inferencing operation
	GeneratedTokenCount uint32 `json:"generated-token-count"`
}

// InferencingModel represents a Large Language Model.
type InferencingModel string

// EmbeddingModel represents the model used for generating embeddings.
type EmbeddingModel string

// EmbeddingsResult represents the result of an embeddings generation request.
type EmbeddingsResult struct {
	// Embeddings are the embeddings generated by the request.
	Embeddings [][]float32
	// Usage is usage related to an embeddings generation request.
	Usage *EmbeddingsUsage
}

// EmbeddingsUsage contains usage information related to an embeddings generation request.
type EmbeddingsUsage struct {
	// PromptTokenCount is number of tokens in the prompt.
	PromptTokenCount int
}

// Infer performs inferencing using the provided model and prompt with the
// given optional parameters.
func Infer(model string, prompt string, params *InferencingParams) (InferencingResult, error) {
	iparams := wit.None[llm.InferencingParams]()
	if params != nil {
		iparams = wit.Some(llm.InferencingParams{
			MaxTokens:                    params.MaxTokens,
			RepeatPenalty:                params.RepeatPenalty,
			RepeatPenaltyLastNTokenCount: params.RepeatPenaltyLastNTokenCount,
			Temperature:                  params.Temperature,
			TopK:                         params.TopK,
			TopP:                         params.TopP,
		})
	}

	result := llm.Infer(llm.InferencingModel(model), prompt, iparams)
	if result.IsErr() {
		return InferencingResult{}, errorVariantToError(result.Err())
	}

	return InferencingResult{
		Text: result.Ok().Text,
		Usage: InferencingUsage{
			PromptTokenCount:    result.Ok().Usage.PromptTokenCount,
			GeneratedTokenCount: result.Ok().Usage.GeneratedTokenCount,
		},
	}, nil
}

// GenerateEmbeddings generates the embeddings for the supplied list of text.
func GenerateEmbeddings(model EmbeddingModel, text []string) (*EmbeddingsResult, error) {
	result := llm.GenerateEmbeddings(llm.EmbeddingModel(model), text)
	if result.IsErr() {
		return &EmbeddingsResult{}, errorVariantToError(result.Err())
	}

	embeddings := [][]float32{}
	for _, l := range result.Ok().Embeddings {
		embeddings = append(embeddings, l)
	}

	return &EmbeddingsResult{
		Embeddings: embeddings,
		Usage: &EmbeddingsUsage{
			PromptTokenCount: int(result.Ok().Usage.PromptTokenCount),
		},
	}, nil
}

func errorVariantToError(err llm.Error) error {
	switch err.Tag() {
	case llm.ErrorModelNotSupported:
		return fmt.Errorf("model not supported")
	case llm.ErrorRuntimeError:
		return fmt.Errorf("runtime error %s", err.RuntimeError())
	case llm.ErrorInvalidInput:
		return fmt.Errorf("invalid input %s", err.InvalidInput())
	default:
		return fmt.Errorf("no error provided by host implementation")
	}
}
