// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_keyvalue_batch

import (
	"github.com/spinframework/spin-go-sdk/v3/internal/wasi_keyvalue_store"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Bucket = wasi_keyvalue_store.Bucket
type Error = wasi_keyvalue_store.Error

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 get-many
func wasm_import_get_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func GetMany(bucket *wasi_keyvalue_store.Bucket, keys []string) witTypes.Result[[]witTypes.Tuple2[string, witTypes.Option[[]uint8]], wasi_keyvalue_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keys
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_get_many((bucket).Handle(), uintptr(result), length, returnArea)
	var result3 witTypes.Result[[]witTypes.Tuple2[string, witTypes.Option[[]uint8]], wasi_keyvalue_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]witTypes.Tuple2[string, witTypes.Option[[]uint8]], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(5*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			var option witTypes.Option[[]uint8]
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))) {
			case 0:

				option = witTypes.None[[]uint8]()
			case 1:
				value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (4 * 4))))

				option = witTypes.Some[[]uint8](value0)
			default:
				panic("unreachable")
			}

			result1 = append(result1, witTypes.Tuple2[string, witTypes.Option[[]uint8]]{value, option})
		}

		result3 = witTypes.Ok[[]witTypes.Tuple2[string, witTypes.Option[[]uint8]], wasi_keyvalue_store.Error](result1)
	case 1:
		var variant wasi_keyvalue_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasi_keyvalue_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_store.MakeErrorAccessDenied()

		case 2:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasi_keyvalue_store.MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result3 = witTypes.Err[[]witTypes.Tuple2[string, witTypes.Option[[]uint8]], wasi_keyvalue_store.Error](variant)
	default:
		panic("unreachable")
	}
	result4 := result3
	return result4

}

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 set-many
func wasm_import_set_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func SetMany(bucket *wasi_keyvalue_store.Bucket, keyValues []witTypes.Tuple2[string, []uint8]) witTypes.Result[witTypes.Unit, wasi_keyvalue_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keyValues
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(4*4))
		utf8 := unsafe.Pointer(unsafe.StringData((element).F0))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
		data := unsafe.Pointer(unsafe.SliceData((element).F1))
		pinner.Pin(data)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(data)))

	}

	wasm_import_set_many((bucket).Handle(), uintptr(result), length, returnArea)
	var result0 witTypes.Result[witTypes.Unit, wasi_keyvalue_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = witTypes.Ok[witTypes.Unit, wasi_keyvalue_store.Error](witTypes.Unit{})
	case 1:
		var variant wasi_keyvalue_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasi_keyvalue_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_store.MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasi_keyvalue_store.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = witTypes.Err[witTypes.Unit, wasi_keyvalue_store.Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result0
	return result1

}

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 delete-many
func wasm_import_delete_many(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func DeleteMany(bucket *wasi_keyvalue_store.Bucket, keys []string) witTypes.Result[witTypes.Unit, wasi_keyvalue_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	slice := keys
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_delete_many((bucket).Handle(), uintptr(result), length, returnArea)
	var result0 witTypes.Result[witTypes.Unit, wasi_keyvalue_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = witTypes.Ok[witTypes.Unit, wasi_keyvalue_store.Error](witTypes.Unit{})
	case 1:
		var variant wasi_keyvalue_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasi_keyvalue_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_store.MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasi_keyvalue_store.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = witTypes.Err[witTypes.Unit, wasi_keyvalue_store.Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result0
	return result1

}
