// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package fermyon_spin_2_0_0_postgres

import (
	"github.com/spinframework/spin-go-sdk/v3/internal/fermyon_spin_2_0_0_rdbms_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type ParameterValue = fermyon_spin_2_0_0_rdbms_types.ParameterValue
type RowSet = fermyon_spin_2_0_0_rdbms_types.RowSet
type Error = fermyon_spin_2_0_0_rdbms_types.Error

//go:wasmimport fermyon:spin/postgres@2.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A connection to a postgres database.
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

//go:wasmimport fermyon:spin/postgres@2.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func ConnectionOpen(address string) witTypes.Result[*Connection, fermyon_spin_2_0_0_rdbms_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), returnArea)
	var result witTypes.Result[*Connection, fermyon_spin_2_0_0_rdbms_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, fermyon_spin_2_0_0_rdbms_types.Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant fermyon_spin_2_0_0_rdbms_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorConnectionFailed(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorBadParameter(value0)

		case 2:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorQueryFailed(value1)

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorValueConversionFailed(value2)

		case 4:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorOther(value3)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, fermyon_spin_2_0_0_rdbms_types.Error](variant)
	default:
		panic("unreachable")
	}
	result4 := result
	return result4

}

//go:wasmimport fermyon:spin/postgres@2.0.0 [method]connection.query
func wasm_import_method_connection_query(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Query(statement string, params []fermyon_spin_2_0_0_rdbms_types.ParameterValue) witTypes.Result[fermyon_spin_2_0_0_rdbms_types.RowSet, fermyon_spin_2_0_0_rdbms_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := params
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*(8+2*4))

		switch element.Tag() {
		case fermyon_spin_2_0_0_rdbms_types.ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_query((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result1), length, returnArea)
	var result13 witTypes.Result[fermyon_spin_2_0_0_rdbms_types.RowSet, fermyon_spin_2_0_0_rdbms_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result2 := make([]fermyon_spin_2_0_0_rdbms_types.Column, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(3*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result2 = append(result2, fermyon_spin_2_0_0_rdbms_types.Column{value, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))})
		}

		result6 := make([][]fermyon_spin_2_0_0_rdbms_types.DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(2*4))
			result5 := make([]fermyon_spin_2_0_0_rdbms_types.DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*(8+2*4))
				var variant fermyon_spin_2_0_0_rdbms_types.DbValue
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
				case 0:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueBoolean((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

				case 1:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueInt8(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 2:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueInt16(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 3:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueInt32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 4:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 5:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueUint8(uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 6:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueUint16(uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 7:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueUint32(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

				case 8:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueUint64(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8))))

				case 9:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueFloating32(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 10:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueFloating64(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 11:
					value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueStr(value3)

				case 12:
					value4 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueBinary(value4)

				case 13:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueDbNull()

				case 14:

					variant = fermyon_spin_2_0_0_rdbms_types.MakeDbValueUnsupported()

				default:
					panic("unreachable")
				}

				result5 = append(result5, variant)
			}

			result6 = append(result6, result5)
		}

		result13 = witTypes.Ok[fermyon_spin_2_0_0_rdbms_types.RowSet, fermyon_spin_2_0_0_rdbms_types.Error](fermyon_spin_2_0_0_rdbms_types.RowSet{result2, result6})
	case 1:
		var variant12 fermyon_spin_2_0_0_rdbms_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = fermyon_spin_2_0_0_rdbms_types.MakeErrorConnectionFailed(value7)

		case 1:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = fermyon_spin_2_0_0_rdbms_types.MakeErrorBadParameter(value8)

		case 2:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = fermyon_spin_2_0_0_rdbms_types.MakeErrorQueryFailed(value9)

		case 3:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = fermyon_spin_2_0_0_rdbms_types.MakeErrorValueConversionFailed(value10)

		case 4:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = fermyon_spin_2_0_0_rdbms_types.MakeErrorOther(value11)

		default:
			panic("unreachable")
		}

		result13 = witTypes.Err[fermyon_spin_2_0_0_rdbms_types.RowSet, fermyon_spin_2_0_0_rdbms_types.Error](variant12)
	default:
		panic("unreachable")
	}
	result14 := result13
	return result14

}

//go:wasmimport fermyon:spin/postgres@2.0.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Execute(statement string, params []fermyon_spin_2_0_0_rdbms_types.ParameterValue) witTypes.Result[uint64, fermyon_spin_2_0_0_rdbms_types.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := params
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*(8+2*4))

		switch element.Tag() {
		case fermyon_spin_2_0_0_rdbms_types.ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case fermyon_spin_2_0_0_rdbms_types.ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result1), length, returnArea)
	var result6 witTypes.Result[uint64, fermyon_spin_2_0_0_rdbms_types.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result6 = witTypes.Ok[uint64, fermyon_spin_2_0_0_rdbms_types.Error](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant fermyon_spin_2_0_0_rdbms_types.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorConnectionFailed(value)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorBadParameter(value2)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorQueryFailed(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorValueConversionFailed(value4)

		case 4:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = fermyon_spin_2_0_0_rdbms_types.MakeErrorOther(value5)

		default:
			panic("unreachable")
		}

		result6 = witTypes.Err[uint64, fermyon_spin_2_0_0_rdbms_types.Error](variant)
	default:
		panic("unreachable")
	}
	result7 := result6
	return result7

}
