// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package fermyon_spin_http_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

type HttpStatus = uint16
type Body = []uint8
type Headers = []witTypes.Tuple2[string, string]
type Params = []witTypes.Tuple2[string, string]
type Uri = string

const (
	MethodGet     uint8 = 0
	MethodPost    uint8 = 1
	MethodPut     uint8 = 2
	MethodDelete  uint8 = 3
	MethodPatch   uint8 = 4
	MethodHead    uint8 = 5
	MethodOptions uint8 = 6
)

type Method = uint8

type Request struct {
	Method  Method
	Uri     string
	Headers []witTypes.Tuple2[string, string]
	Params  []witTypes.Tuple2[string, string]
	Body    witTypes.Option[[]uint8]
}

type Response struct {
	Status  uint16
	Headers witTypes.Option[[]witTypes.Tuple2[string, string]]
	Body    witTypes.Option[[]uint8]
}

const (
	HttpErrorSuccess               uint8 = 0
	HttpErrorDestinationNotAllowed uint8 = 1
	HttpErrorInvalidUrl            uint8 = 2
	HttpErrorRequestError          uint8 = 3
	HttpErrorRuntimeError          uint8 = 4
	HttpErrorTooManyRequests       uint8 = 5
)

type HttpError = uint8
