// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package fermyon_spin_key_value

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

// A handle to an open key-value store
type Store = uint32

const (
	// Too many stores have been opened simultaneously. Closing one or more
	// stores prior to retrying may address this.
	ErrorStoreTableFull uint8 = 0
	// The host does not recognize the store name requested.  Defining and
	// configuring a store with that name in a runtime configuration file
	// may address this.
	ErrorNoSuchStore uint8 = 1
	// The requesting component does not have access to the specified store
	// (which may or may not exist).
	ErrorAccessDenied uint8 = 2
	// The store handle provided is not recognized, i.e. it was either never
	// opened or has been closed.
	ErrorInvalidStore uint8 = 3
	// No key-value tuple exists for the specified key in the specified
	// store.
	ErrorNoSuchKey uint8 = 4
	// Some implementation-specific error has occurred (e.g. I/O)
	ErrorIo uint8 = 5
)

// The set of errors which may be raised by functions in this interface
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Io() string {
	if self.tag != ErrorIo {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorStoreTableFull() Error {
	return Error{ErrorStoreTableFull, nil}
}
func MakeErrorNoSuchStore() Error {
	return Error{ErrorNoSuchStore, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorInvalidStore() Error {
	return Error{ErrorInvalidStore, nil}
}
func MakeErrorNoSuchKey() Error {
	return Error{ErrorNoSuchKey, nil}
}
func MakeErrorIo(value string) Error {
	return Error{ErrorIo, value}
}

//go:wasmimport fermyon:spin/key-value open
func wasm_import_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Open(name string) witTypes.Result[uint32, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)
	wasm_import_open(uintptr(utf8), uint32(len(name)), returnArea)
	var result witTypes.Result[uint32, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint32, Error](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint32, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/key-value get
func wasm_import_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func Get(store uint32, key string) witTypes.Result[[]uint8, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_get(int32(store), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[[]uint8, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, Error](value)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/key-value set
func wasm_import_set(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func Set(store uint32, key string, value []uint8) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_set(int32(store), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/key-value delete
func wasm_import_delete(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func Delete(store uint32, key string) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_delete(int32(store), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/key-value exists
func wasm_import_exists(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func Exists(store uint32, key string) witTypes.Result[bool, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_exists(int32(store), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[bool, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[bool, Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[bool, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/key-value get-keys
func wasm_import_get_keys(arg0 int32, arg1 uintptr)

func GetKeys(store uint32) witTypes.Result[[]string, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	wasm_import_get_keys(int32(store), returnArea)
	var result1 witTypes.Result[[]string, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result1 = witTypes.Ok[[]string, Error](result)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:

			variant = MakeErrorInvalidStore()

		case 4:

			variant = MakeErrorNoSuchKey()

		case 5:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value0)

		default:
			panic("unreachable")
		}

		result1 = witTypes.Err[[]string, Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/key-value close
func wasm_import_close(arg0 int32)

func Close(store uint32) {

	wasm_import_close(int32(store))

}
