// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package fermyon_spin_2_0_0_mqtt

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

const (
	// An invalid address string
	ErrorInvalidAddress uint8 = 0
	// There are too many open connections
	ErrorTooManyConnections uint8 = 1
	// Connection failure e.g. address not allowed.
	ErrorConnectionFailed uint8 = 2
	// Some other error occurred
	ErrorOther uint8 = 3
)

// Errors related to interacting with Mqtt
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) ConnectionFailed() string {
	if self.tag != ErrorConnectionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorInvalidAddress() Error {
	return Error{ErrorInvalidAddress, nil}
}
func MakeErrorTooManyConnections() Error {
	return Error{ErrorTooManyConnections, nil}
}
func MakeErrorConnectionFailed(value string) Error {
	return Error{ErrorConnectionFailed, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

const (
	QosAtMostOnce  uint8 = 0
	QosAtLeastOnce uint8 = 1
	QosExactlyOnce uint8 = 2
)

// QoS for publishing Mqtt messages
type Qos = uint8

//go:wasmimport fermyon:spin/mqtt@2.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

// The message payload.
type Payload = []uint8

//go:wasmimport fermyon:spin/mqtt@2.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 int64, arg7 uintptr)

func ConnectionOpen(address string, username string, password string, keepAliveIntervalInSecs uint64) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(username))
	pinner.Pin(utf80)
	utf81 := unsafe.Pointer(unsafe.StringData(password))
	pinner.Pin(utf81)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(username)), uintptr(utf81), uint32(len(password)), int64(keepAliveIntervalInSecs), returnArea)
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}
	result3 := result
	return result3

}

//go:wasmimport fermyon:spin/mqtt@2.0.0 [method]connection.publish
func wasm_import_method_connection_publish(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 int32, arg6 uintptr)

func (self *Connection) Publish(topic string, payload []uint8, qos Qos) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(topic))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(payload))
	pinner.Pin(data)
	wasm_import_method_connection_publish((self).Handle(), uintptr(utf8), uint32(len(topic)), uintptr(data), uint32(len(payload)), int32(qos), returnArea)
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}
