// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package fermyon_spin_http

import (
	"github.com/spinframework/spin-go-sdk/v3/redis_internal/fermyon_spin_http_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Request = fermyon_spin_http_types.Request
type Response = fermyon_spin_http_types.Response
type HttpError = fermyon_spin_http_types.HttpError

//go:wasmimport fermyon:spin/http send-request
func wasm_import_send_request(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr, arg6 uint32, arg7 int32, arg8 uintptr, arg9 uint32, arg10 uintptr)

func SendRequest(req fermyon_spin_http_types.Request) witTypes.Result[fermyon_spin_http_types.Response, fermyon_spin_http_types.HttpError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData((req).Uri))
	pinner.Pin(utf8)
	slice := (req).Headers
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(4*4))
		utf80 := unsafe.Pointer(unsafe.StringData((element).F0))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))
		utf81 := unsafe.Pointer(unsafe.StringData((element).F1))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf81)))

	}

	slice4 := (req).Params
	length6 := uint32(len(slice4))
	result5 := witRuntime.Allocate(pinner, uintptr(length6*(4*4)), 4)
	for index, element := range slice4 {
		base := unsafe.Add(result5, index*(4*4))
		utf82 := unsafe.Pointer(unsafe.StringData((element).F0))
		pinner.Pin(utf82)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf82)))
		utf83 := unsafe.Pointer(unsafe.StringData((element).F1))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf83)))

	}

	var option int32
	var option7 uintptr
	var option8 uint32
	switch (req).Body.Tag() {
	case witTypes.OptionNone:

		option = int32(0)
		option7 = 0
		option8 = 0
	case witTypes.OptionSome:
		payload := (req).Body.Some()
		data := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data)

		option = int32(1)
		option7 = uintptr(data)
		option8 = uint32(len(payload))
	default:
		panic("unreachable")
	}
	wasm_import_send_request(int32((req).Method), uintptr(utf8), uint32(len((req).Uri)), uintptr(result), length, uintptr(result5), length6, option, option7, option8, returnArea)
	var result14 witTypes.Result[fermyon_spin_http_types.Response, fermyon_spin_http_types.HttpError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option11 witTypes.Option[[]witTypes.Tuple2[string, string]]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
		case 0:

			option11 = witTypes.None[[]witTypes.Tuple2[string, string]]()
		case 1:
			result10 := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(4*4))
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
				value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

				result10 = append(result10, witTypes.Tuple2[string, string]{value, value9})
			}

			option11 = witTypes.Some[[]witTypes.Tuple2[string, string]](result10)
		default:
			panic("unreachable")
		}
		var option13 witTypes.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4)))) {
		case 0:

			option13 = witTypes.None[[]uint8]()
		case 1:
			value12 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (6 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (7 * 4))))

			option13 = witTypes.Some[[]uint8](value12)
		default:
			panic("unreachable")
		}

		result14 = witTypes.Ok[fermyon_spin_http_types.Response, fermyon_spin_http_types.HttpError](fermyon_spin_http_types.Response{uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), option11, option13})
	case 1:

		result14 = witTypes.Err[fermyon_spin_http_types.Response, fermyon_spin_http_types.HttpError](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result15 := result14
	return result15

}
