// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package spin_key_value_3_0_0_key_value

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport spin:key-value/key-value@3.0.0 [stream-new-0][method]store.get-keys
func wasm_stream_new_string() uint64

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][stream-read-0][method]store.get-keys
func wasm_stream_read_string(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][stream-write-0][method]store.get-keys
func wasm_stream_write_string(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:key-value/key-value@3.0.0 [stream-drop-readable-0][method]store.get-keys
func wasm_stream_drop_readable_string(handle int32)

//go:wasmimport spin:key-value/key-value@3.0.0 [stream-drop-writable-0][method]store.get-keys
func wasm_stream_drop_writable_string(handle int32)

func wasm_stream_lift_string(src unsafe.Pointer) string {
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), 4)))

	return value
}

func wasm_stream_lower_string(
	pinner *runtime.Pinner,
	value string,
	dst unsafe.Pointer,
) func() {
	utf8 := unsafe.Pointer(unsafe.StringData(value))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 4)) = uint32(uint32(len(value)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 0)) = uint32(uintptr(uintptr(utf8)))

	return func() {}
}

var wasm_stream_vtable_string = witTypes.StreamVtable[string]{
	(2 * 4),
	4,
	wasm_stream_read_string,
	wasm_stream_write_string,
	nil,
	nil,
	wasm_stream_drop_readable_string,
	wasm_stream_drop_writable_string,
	wasm_stream_lift_string,
	wasm_stream_lower_string,
}

func MakeStreamString() (*witTypes.StreamWriter[string], *witTypes.StreamReader[string]) {
	pair := wasm_stream_new_string()
	return witTypes.MakeStreamWriter[string](&wasm_stream_vtable_string, int32(pair>>32)),
		witTypes.MakeStreamReader[string](&wasm_stream_vtable_string, int32(pair&0xFFFFFFFF))
}

func LiftStreamString(handle int32) *witTypes.StreamReader[string] {
	return witTypes.MakeStreamReader[string](&wasm_stream_vtable_string, handle)
}

//go:wasmimport spin:key-value/key-value@3.0.0 [future-new-1][method]store.get-keys
func wasm_future_new_result_unit_error() uint64

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][future-read-1][method]store.get-keys
func wasm_future_read_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][future-write-1][method]store.get-keys
func wasm_future_write_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:key-value/key-value@3.0.0 [future-drop-readable-1][method]store.get-keys
func wasm_future_drop_readable_result_unit_error(handle int32)

//go:wasmimport spin:key-value/key-value@3.0.0 [future-drop-writable-1][method]store.get-keys
func wasm_future_drop_writable_result_unit_error(handle int32)

func wasm_future_lift_result_unit_error(src unsafe.Pointer) witTypes.Result[witTypes.Unit, Error] {
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_error(
	pinner *runtime.Pinner,
	value witTypes.Result[witTypes.Unit, Error],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))

		switch payload.Tag() {
		case ErrorStoreTableFull:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(0))

		case ErrorNoSuchStore:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(1))

		case ErrorAccessDenied:

			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(2))

		case ErrorOther:
			payload := payload.Other()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(3))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_error = witTypes.FutureVtable[witTypes.Result[witTypes.Unit, Error]]{
	(4 * 4),
	4,
	wasm_future_read_result_unit_error,
	wasm_future_write_result_unit_error,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_error,
	wasm_future_drop_writable_result_unit_error,
	wasm_future_lift_result_unit_error,
	wasm_future_lower_result_unit_error,
}

func MakeFutureResultUnitError() (*witTypes.FutureWriter[witTypes.Result[witTypes.Unit, Error]], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]) {
	pair := wasm_future_new_result_unit_error()
	return witTypes.MakeFutureWriter[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair>>32)),
		witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitError(handle int32) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]] {
	return witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, handle)
}

//go:wasmimport spin:key-value/key-value@3.0.0 [resource-drop]store
func resourceDropStore(handle int32)

// An open key-value store
type Store struct {
	handle *witRuntime.Handle
}

func (self *Store) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Store) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Store) Handle() int32 {
	return self.handle.Use()
}

func (self *Store) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropStore(handle)
	}
}

func StoreFromOwnHandle(handleValue int32) *Store {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Store{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropStore(handleValue)
		}
	}, 0)
	return value
}

func StoreFromBorrowHandle(handleValue int32) *Store {
	handle := witRuntime.MakeHandle(handleValue)
	return &Store{handle}
}

const (
	// Too many stores have been opened simultaneously. Closing one or more
	// stores prior to retrying may address this.
	ErrorStoreTableFull uint8 = 0
	// The host does not recognize the store label requested.
	ErrorNoSuchStore uint8 = 1
	// The requesting component does not have access to the specified store
	// (which may or may not exist).
	ErrorAccessDenied uint8 = 2
	// Some implementation-specific error has occurred (e.g. I/O)
	ErrorOther uint8 = 3
)

// The set of errors which may be raised by functions in this interface
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorStoreTableFull() Error {
	return Error{ErrorStoreTableFull, nil}
}
func MakeErrorNoSuchStore() Error {
	return Error{ErrorNoSuchStore, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][static]store.open
func wasm_import_static_store_open(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func StoreOpen(label string) witTypes.Result[*Store, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(label))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_static_store_open(uintptr(utf8), uint32(len(label)), returnArea)))
	var result witTypes.Result[*Store, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Store, Error](StoreFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Store, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][method]store.get
func wasm_import_method_store_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Store) Get(key string) witTypes.Result[witTypes.Option[[]uint8], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_store_get((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[witTypes.Option[[]uint8], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = witTypes.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			option = witTypes.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[[]uint8], Error](option)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[[]uint8], Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][method]store.set
func wasm_import_method_store_set(arg0 uintptr, arg1 uintptr) int32

func (self *Store) Set(key string, value []uint8) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params := witRuntime.Allocate(pinner, (5 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 4)) = uint32(uint32(len(key)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 4)) = uint32(uint32(len(value)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params), (3*4))), 0)) = uint32(uintptr(uintptr(data)))

	witAsync.SubtaskWait(uint32(wasm_import_method_store_set(uintptr(params), returnArea)))
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][method]store.delete
func wasm_import_method_store_delete(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Store) Delete(key string) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_store_delete((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][method]store.exists
func wasm_import_method_store_exists(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr) int32

func (self *Store) Exists(key string) witTypes.Result[bool, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_method_store_exists((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)))
	var result witTypes.Result[bool, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[bool, Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorStoreTableFull()

		case 1:

			variant = MakeErrorNoSuchStore()

		case 2:

			variant = MakeErrorAccessDenied()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[bool, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:key-value/key-value@3.0.0 [async-lower][method]store.get-keys
func wasm_import_method_store_get_keys(arg0 int32, arg1 uintptr) int32

func (self *Store) GetKeys() (*witTypes.StreamReader[string], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))

	witAsync.SubtaskWait(uint32(wasm_import_method_store_get_keys((self).Handle(), returnArea)))

	tuple := witTypes.Tuple2[*witTypes.StreamReader[string], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]]{LiftStreamString(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), LiftFutureResultUnitError(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))}
	return tuple.F0, tuple.F1

}
