// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.2.0-rc-2023-11-10
//     wasi:http@0.3.0-rc-2026-03-15
//     componentize-go:union

package wasi_clocks_0_3_0_rc_2026_03_15_monotonic_clock

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
)

type Duration = uint64

// A mark on a monotonic clock is a number of nanoseconds since an
// unspecified initial value, and can only be compared to instances from
// the same monotonic-clock.
type Mark = uint64

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15 now
func wasm_import_now() int64

func Now() uint64 {

	result := wasm_import_now()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15 get-resolution
func wasm_import_get_resolution() int64

func GetResolution() uint64 {

	result := wasm_import_get_resolution()
	return uint64(result)

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15 [async-lower]wait-until
func wasm_import_wait_until(arg0 int64) int32

func WaitUntil(when uint64) {

	witAsync.SubtaskWait(uint32(wasm_import_wait_until(int64(when))))

}

//go:wasmimport wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15 [async-lower]wait-for
func wasm_import_wait_for(arg0 int64) int32

func WaitFor(howLong uint64) {

	witAsync.SubtaskWait(uint32(wasm_import_wait_for(int64(howLong))))

}
