// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_cli_0_3_0_rc_2026_03_15_stdout

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_cli_0_3_0_rc_2026_03_15_types"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 [future-new-1]write-via-stream
func wasm_future_new_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code() uint64

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 [async-lower][future-read-1]write-via-stream
func wasm_future_read_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 [async-lower][future-write-1]write-via-stream
func wasm_future_write_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(handle int32, item unsafe.Pointer) uint32

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 [future-drop-readable-1]write-via-stream
func wasm_future_drop_readable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(handle int32)

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 [future-drop-writable-1]write-via-stream
func wasm_future_drop_writable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(handle int32)

func wasm_future_lift_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(src unsafe.Pointer) witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode] {
	var result witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode](witTypes.Unit{})
	case 1:

		result = witTypes.Err[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 1)))))
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code(
	pinner *runtime.Pinner,
	value witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 1)) = int8(int32(payload))

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code = witTypes.FutureVtable[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]]{
	2,
	1,
	wasm_future_read_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
	wasm_future_write_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
	wasm_future_drop_writable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
	wasm_future_lift_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
	wasm_future_lower_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code,
}

func MakeFutureResultUnitWasiCli030Rc20260315TypesErrorCode() (*witTypes.FutureWriter[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]]) {
	pair := wasm_future_new_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code()
	return witTypes.MakeFutureWriter[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code, int32(pair>>32)),
		witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitWasiCli030Rc20260315TypesErrorCode(handle int32) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]] {
	return witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]](&wasm_future_vtable_result_unit_wasi_cli_0_3_0_rc_2026_03_15_types_error_code, handle)
}

type ErrorCode = wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode

//go:wasmimport wasi:cli/stdout@0.3.0-rc-2026-03-15 write-via-stream
func wasm_import_write_via_stream(arg0 int32) int32

func WriteViaStream(data *witTypes.StreamReader[uint8]) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, wasi_cli_0_3_0_rc_2026_03_15_types.ErrorCode]] {

	result := wasm_import_write_via_stream((data).TakeHandle())
	return LiftFutureResultUnitWasiCli030Rc20260315TypesErrorCode(result)

}
