// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:mysql@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:clocks@0.3.0
//     wasi:filesystem@0.3.0
//     wasi:sockets@0.3.0
//     wasi:random@0.3.0
//     wasi:cli@0.3.0
//     wasi:http@0.3.0
//     spin:up@4.1.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package spin_mysql_3_0_0_mysql

import (
	witAsync "go.bytecodealliance.org/pkg/wit/async"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport spin:mysql/mysql@3.0.0 [stream-new-0][method]connection.query
func wasm_stream_new_list_db_value() uint64

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][stream-read-0][method]connection.query
func wasm_stream_read_list_db_value(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][stream-write-0][method]connection.query
func wasm_stream_write_list_db_value(handle int32, item unsafe.Pointer, count uint32) uint32

//go:wasmimport spin:mysql/mysql@3.0.0 [stream-drop-readable-0][method]connection.query
func wasm_stream_drop_readable_list_db_value(handle int32)

//go:wasmimport spin:mysql/mysql@3.0.0 [stream-drop-writable-0][method]connection.query
func wasm_stream_drop_writable_list_db_value(handle int32)

func wasm_stream_lift_list_db_value(src unsafe.Pointer) []DbValue {
	result := make([]DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(src), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0)))), index*(8+2*4))
		var variant DbValue
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
		case 0:

			variant = MakeDbValueBoolean((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

		case 1:

			variant = MakeDbValueInt8(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

		case 2:

			variant = MakeDbValueInt16(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

		case 3:

			variant = MakeDbValueInt32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 4:

			variant = MakeDbValueInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 5:

			variant = MakeDbValueUint8(uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

		case 6:

			variant = MakeDbValueUint16(uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

		case 7:

			variant = MakeDbValueUint32(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

		case 8:

			variant = MakeDbValueUint64(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8))))

		case 9:

			variant = MakeDbValueFloating32(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 10:

			variant = MakeDbValueFloating64(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

		case 11:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

			variant = MakeDbValueStr(value)

		case 12:
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

			variant = MakeDbValueBinary(value0)

		case 13:

			variant = MakeDbValueDbNull()

		case 14:

			variant = MakeDbValueUnsupported()

		default:
			panic("unreachable")
		}

		result = append(result, variant)
	}

	return result
}

func wasm_stream_lower_list_db_value(
	pinner *runtime.Pinner,
	value []DbValue,
	dst unsafe.Pointer,
) func() {
	slice := value
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(8+2*4))

		switch element.Tag() {
		case DbValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result1 int32
			if payload {
				result1 = 1
			} else {
				result1 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result1)

		case DbValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case DbValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case DbValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case DbValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case DbValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case DbValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case DbValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case DbValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case DbValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case DbValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case DbValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf8)))

		case DbValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case DbValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		case DbValueUnsupported:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(14))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(dst), 0)) = uint32(uintptr(uintptr(result2)))

	return func() {}
}

var wasm_stream_vtable_list_db_value = witTypes.StreamVtable[[]DbValue]{
	(2 * 4),
	4,
	wasm_stream_read_list_db_value,
	wasm_stream_write_list_db_value,
	nil,
	nil,
	wasm_stream_drop_readable_list_db_value,
	wasm_stream_drop_writable_list_db_value,
	wasm_stream_lift_list_db_value,
	wasm_stream_lower_list_db_value,
}

func MakeStreamListDbValue() (*witTypes.StreamWriter[[]DbValue], *witTypes.StreamReader[[]DbValue]) {
	pair := wasm_stream_new_list_db_value()
	return witTypes.MakeStreamWriter[[]DbValue](&wasm_stream_vtable_list_db_value, int32(pair>>32)),
		witTypes.MakeStreamReader[[]DbValue](&wasm_stream_vtable_list_db_value, int32(pair&0xFFFFFFFF))
}

func LiftStreamListDbValue(handle int32) *witTypes.StreamReader[[]DbValue] {
	return witTypes.MakeStreamReader[[]DbValue](&wasm_stream_vtable_list_db_value, handle)
}

//go:wasmimport spin:mysql/mysql@3.0.0 [future-new-1][method]connection.query
func wasm_future_new_result_unit_error() uint64

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][future-read-1][method]connection.query
func wasm_future_read_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][future-write-1][method]connection.query
func wasm_future_write_result_unit_error(handle int32, item unsafe.Pointer) uint32

//go:wasmimport spin:mysql/mysql@3.0.0 [future-drop-readable-1][method]connection.query
func wasm_future_drop_readable_result_unit_error(handle int32)

//go:wasmimport spin:mysql/mysql@3.0.0 [future-drop-writable-1][method]connection.query
func wasm_future_drop_writable_result_unit_error(handle int32)

func wasm_future_lift_result_unit_error(src unsafe.Pointer) witTypes.Result[witTypes.Unit, Error] {
	var result witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(src), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorBadParameter(value0)

		case 2:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorQueryFailed(value1)

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorValueConversionFailed(value2)

		case 4:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(src), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(src), (3 * 4))))

			variant = MakeErrorOther(value3)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result
}

func wasm_future_lower_result_unit_error(
	pinner *runtime.Pinner,
	value witTypes.Result[witTypes.Unit, Error],
	dst unsafe.Pointer,
) func() {

	switch value.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := value.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(dst), 0)) = int8(int32(1))

		switch payload.Tag() {
		case ErrorConnectionFailed:
			payload := payload.ConnectionFailed()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(0))
			utf8 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf8)))

		case ErrorBadParameter:
			payload := payload.BadParameter()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(1))
			utf84 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf84)))

		case ErrorQueryFailed:
			payload := payload.QueryFailed()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(2))
			utf85 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf85)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf85)))

		case ErrorValueConversionFailed:
			payload := payload.ValueConversionFailed()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(3))
			utf86 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf86)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf86)))

		case ErrorOther:
			payload := payload.Other()
			*(*int8)(unsafe.Add(unsafe.Pointer(dst), 4)) = int8(int32(4))
			utf87 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf87)
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (3 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(dst), (2 * 4))) = uint32(uintptr(uintptr(utf87)))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}

	return func() {}
}

var wasm_future_vtable_result_unit_error = witTypes.FutureVtable[witTypes.Result[witTypes.Unit, Error]]{
	(4 * 4),
	4,
	wasm_future_read_result_unit_error,
	wasm_future_write_result_unit_error,
	nil,
	nil,
	wasm_future_drop_readable_result_unit_error,
	wasm_future_drop_writable_result_unit_error,
	wasm_future_lift_result_unit_error,
	wasm_future_lower_result_unit_error,
}

func MakeFutureResultUnitError() (*witTypes.FutureWriter[witTypes.Result[witTypes.Unit, Error]], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]) {
	pair := wasm_future_new_result_unit_error()
	return witTypes.MakeFutureWriter[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair>>32)),
		witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, int32(pair&0xFFFFFFFF))
}

func LiftFutureResultUnitError(handle int32) *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]] {
	return witTypes.MakeFutureReader[witTypes.Result[witTypes.Unit, Error]](&wasm_future_vtable_result_unit_error, handle)
}

const (
	ErrorConnectionFailed      uint8 = 0
	ErrorBadParameter          uint8 = 1
	ErrorQueryFailed           uint8 = 2
	ErrorValueConversionFailed uint8 = 3
	ErrorOther                 uint8 = 4
)

// Errors related to interacting with a database.
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) ConnectionFailed() string {
	if self.tag != ErrorConnectionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) BadParameter() string {
	if self.tag != ErrorBadParameter {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) QueryFailed() string {
	if self.tag != ErrorQueryFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) ValueConversionFailed() string {
	if self.tag != ErrorValueConversionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorConnectionFailed(value string) Error {
	return Error{ErrorConnectionFailed, value}
}
func MakeErrorBadParameter(value string) Error {
	return Error{ErrorBadParameter, value}
}
func MakeErrorQueryFailed(value string) Error {
	return Error{ErrorQueryFailed, value}
}
func MakeErrorValueConversionFailed(value string) Error {
	return Error{ErrorValueConversionFailed, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

const (
	DbDataTypeBoolean    uint8 = 0
	DbDataTypeInt8       uint8 = 1
	DbDataTypeInt16      uint8 = 2
	DbDataTypeInt32      uint8 = 3
	DbDataTypeInt64      uint8 = 4
	DbDataTypeUint8      uint8 = 5
	DbDataTypeUint16     uint8 = 6
	DbDataTypeUint32     uint8 = 7
	DbDataTypeUint64     uint8 = 8
	DbDataTypeFloating32 uint8 = 9
	DbDataTypeFloating64 uint8 = 10
	DbDataTypeStr        uint8 = 11
	DbDataTypeBinary     uint8 = 12
	DbDataTypeOther      uint8 = 13
)

// Data types for a database column
type DbDataType = uint8

const (
	DbValueBoolean     uint8 = 0
	DbValueInt8        uint8 = 1
	DbValueInt16       uint8 = 2
	DbValueInt32       uint8 = 3
	DbValueInt64       uint8 = 4
	DbValueUint8       uint8 = 5
	DbValueUint16      uint8 = 6
	DbValueUint32      uint8 = 7
	DbValueUint64      uint8 = 8
	DbValueFloating32  uint8 = 9
	DbValueFloating64  uint8 = 10
	DbValueStr         uint8 = 11
	DbValueBinary      uint8 = 12
	DbValueDbNull      uint8 = 13
	DbValueUnsupported uint8 = 14
)

// Database values
type DbValue struct {
	tag   uint8
	value any
}

func (self DbValue) Tag() uint8 {
	return self.tag
}

func (self DbValue) Boolean() bool {
	if self.tag != DbValueBoolean {
		panic("tag mismatch")
	}
	return self.value.(bool)
}
func (self DbValue) Int8() int8 {
	if self.tag != DbValueInt8 {
		panic("tag mismatch")
	}
	return self.value.(int8)
}
func (self DbValue) Int16() int16 {
	if self.tag != DbValueInt16 {
		panic("tag mismatch")
	}
	return self.value.(int16)
}
func (self DbValue) Int32() int32 {
	if self.tag != DbValueInt32 {
		panic("tag mismatch")
	}
	return self.value.(int32)
}
func (self DbValue) Int64() int64 {
	if self.tag != DbValueInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self DbValue) Uint8() uint8 {
	if self.tag != DbValueUint8 {
		panic("tag mismatch")
	}
	return self.value.(uint8)
}
func (self DbValue) Uint16() uint16 {
	if self.tag != DbValueUint16 {
		panic("tag mismatch")
	}
	return self.value.(uint16)
}
func (self DbValue) Uint32() uint32 {
	if self.tag != DbValueUint32 {
		panic("tag mismatch")
	}
	return self.value.(uint32)
}
func (self DbValue) Uint64() uint64 {
	if self.tag != DbValueUint64 {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self DbValue) Floating32() float32 {
	if self.tag != DbValueFloating32 {
		panic("tag mismatch")
	}
	return self.value.(float32)
}
func (self DbValue) Floating64() float64 {
	if self.tag != DbValueFloating64 {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self DbValue) Str() string {
	if self.tag != DbValueStr {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self DbValue) Binary() []uint8 {
	if self.tag != DbValueBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeDbValueBoolean(value bool) DbValue {
	return DbValue{DbValueBoolean, value}
}
func MakeDbValueInt8(value int8) DbValue {
	return DbValue{DbValueInt8, value}
}
func MakeDbValueInt16(value int16) DbValue {
	return DbValue{DbValueInt16, value}
}
func MakeDbValueInt32(value int32) DbValue {
	return DbValue{DbValueInt32, value}
}
func MakeDbValueInt64(value int64) DbValue {
	return DbValue{DbValueInt64, value}
}
func MakeDbValueUint8(value uint8) DbValue {
	return DbValue{DbValueUint8, value}
}
func MakeDbValueUint16(value uint16) DbValue {
	return DbValue{DbValueUint16, value}
}
func MakeDbValueUint32(value uint32) DbValue {
	return DbValue{DbValueUint32, value}
}
func MakeDbValueUint64(value uint64) DbValue {
	return DbValue{DbValueUint64, value}
}
func MakeDbValueFloating32(value float32) DbValue {
	return DbValue{DbValueFloating32, value}
}
func MakeDbValueFloating64(value float64) DbValue {
	return DbValue{DbValueFloating64, value}
}
func MakeDbValueStr(value string) DbValue {
	return DbValue{DbValueStr, value}
}
func MakeDbValueBinary(value []uint8) DbValue {
	return DbValue{DbValueBinary, value}
}
func MakeDbValueDbNull() DbValue {
	return DbValue{DbValueDbNull, nil}
}
func MakeDbValueUnsupported() DbValue {
	return DbValue{DbValueUnsupported, nil}
}

const (
	ParameterValueBoolean    uint8 = 0
	ParameterValueInt8       uint8 = 1
	ParameterValueInt16      uint8 = 2
	ParameterValueInt32      uint8 = 3
	ParameterValueInt64      uint8 = 4
	ParameterValueUint8      uint8 = 5
	ParameterValueUint16     uint8 = 6
	ParameterValueUint32     uint8 = 7
	ParameterValueUint64     uint8 = 8
	ParameterValueFloating32 uint8 = 9
	ParameterValueFloating64 uint8 = 10
	ParameterValueStr        uint8 = 11
	ParameterValueBinary     uint8 = 12
	ParameterValueDbNull     uint8 = 13
)

// Values used in parameterized queries
type ParameterValue struct {
	tag   uint8
	value any
}

func (self ParameterValue) Tag() uint8 {
	return self.tag
}

func (self ParameterValue) Boolean() bool {
	if self.tag != ParameterValueBoolean {
		panic("tag mismatch")
	}
	return self.value.(bool)
}
func (self ParameterValue) Int8() int8 {
	if self.tag != ParameterValueInt8 {
		panic("tag mismatch")
	}
	return self.value.(int8)
}
func (self ParameterValue) Int16() int16 {
	if self.tag != ParameterValueInt16 {
		panic("tag mismatch")
	}
	return self.value.(int16)
}
func (self ParameterValue) Int32() int32 {
	if self.tag != ParameterValueInt32 {
		panic("tag mismatch")
	}
	return self.value.(int32)
}
func (self ParameterValue) Int64() int64 {
	if self.tag != ParameterValueInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self ParameterValue) Uint8() uint8 {
	if self.tag != ParameterValueUint8 {
		panic("tag mismatch")
	}
	return self.value.(uint8)
}
func (self ParameterValue) Uint16() uint16 {
	if self.tag != ParameterValueUint16 {
		panic("tag mismatch")
	}
	return self.value.(uint16)
}
func (self ParameterValue) Uint32() uint32 {
	if self.tag != ParameterValueUint32 {
		panic("tag mismatch")
	}
	return self.value.(uint32)
}
func (self ParameterValue) Uint64() uint64 {
	if self.tag != ParameterValueUint64 {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self ParameterValue) Floating32() float32 {
	if self.tag != ParameterValueFloating32 {
		panic("tag mismatch")
	}
	return self.value.(float32)
}
func (self ParameterValue) Floating64() float64 {
	if self.tag != ParameterValueFloating64 {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self ParameterValue) Str() string {
	if self.tag != ParameterValueStr {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self ParameterValue) Binary() []uint8 {
	if self.tag != ParameterValueBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeParameterValueBoolean(value bool) ParameterValue {
	return ParameterValue{ParameterValueBoolean, value}
}
func MakeParameterValueInt8(value int8) ParameterValue {
	return ParameterValue{ParameterValueInt8, value}
}
func MakeParameterValueInt16(value int16) ParameterValue {
	return ParameterValue{ParameterValueInt16, value}
}
func MakeParameterValueInt32(value int32) ParameterValue {
	return ParameterValue{ParameterValueInt32, value}
}
func MakeParameterValueInt64(value int64) ParameterValue {
	return ParameterValue{ParameterValueInt64, value}
}
func MakeParameterValueUint8(value uint8) ParameterValue {
	return ParameterValue{ParameterValueUint8, value}
}
func MakeParameterValueUint16(value uint16) ParameterValue {
	return ParameterValue{ParameterValueUint16, value}
}
func MakeParameterValueUint32(value uint32) ParameterValue {
	return ParameterValue{ParameterValueUint32, value}
}
func MakeParameterValueUint64(value uint64) ParameterValue {
	return ParameterValue{ParameterValueUint64, value}
}
func MakeParameterValueFloating32(value float32) ParameterValue {
	return ParameterValue{ParameterValueFloating32, value}
}
func MakeParameterValueFloating64(value float64) ParameterValue {
	return ParameterValue{ParameterValueFloating64, value}
}
func MakeParameterValueStr(value string) ParameterValue {
	return ParameterValue{ParameterValueStr, value}
}
func MakeParameterValueBinary(value []uint8) ParameterValue {
	return ParameterValue{ParameterValueBinary, value}
}
func MakeParameterValueDbNull() ParameterValue {
	return ParameterValue{ParameterValueDbNull, nil}
}

// A database column
type Column struct {
	Name     string
	DataType DbDataType
}

// A database row
type Row = []DbValue

//go:wasmimport spin:mysql/mysql@3.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A connection to a MySQL database.
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr) int32

func ConnectionOpen(address string) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)

	witAsync.SubtaskWait(uint32(wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), returnArea)))
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorBadParameter(value0)

		case 2:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorQueryFailed(value1)

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorValueConversionFailed(value2)

		case 4:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value3)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}

	return result

}

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][method]connection.query
func wasm_import_method_connection_query(arg0 uintptr, arg1 uintptr) int32

func (self *Connection) Query(statement string, params []ParameterValue) witTypes.Result[witTypes.Tuple3[[]Column, *witTypes.StreamReader[[]DbValue], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (8 + 3*4), 4))
	params0 := witRuntime.Allocate(pinner, (5 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 4)), 4)) = uint32(uint32(len(statement)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	slice := params
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(8+2*4))

		switch element.Tag() {
		case ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

		case ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), (3*4))), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), (3*4))), 0)) = uint32(uintptr(uintptr(result2)))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_query(uintptr(params0), returnArea)))
	var result9 witTypes.Result[witTypes.Tuple3[[]Column, *witTypes.StreamReader[[]DbValue], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result3 := make([]Column, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(3*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result3 = append(result3, Column{value, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))})
		}

		result9 = witTypes.Ok[witTypes.Tuple3[[]Column, *witTypes.StreamReader[[]DbValue], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error](witTypes.Tuple3[[]Column, *witTypes.StreamReader[[]DbValue], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]]{result3, LiftStreamListDbValue(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))), LiftFutureResultUnitError(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 3*4))))})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value4)

		case 1:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorBadParameter(value5)

		case 2:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorQueryFailed(value6)

		case 3:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorValueConversionFailed(value7)

		case 4:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value8)

		default:
			panic("unreachable")
		}

		result9 = witTypes.Err[witTypes.Tuple3[[]Column, *witTypes.StreamReader[[]DbValue], *witTypes.FutureReader[witTypes.Result[witTypes.Unit, Error]]], Error](variant)
	default:
		panic("unreachable")
	}

	return result9

}

//go:wasmimport spin:mysql/mysql@3.0.0 [async-lower][method]connection.execute
func wasm_import_method_connection_execute(arg0 uintptr, arg1 uintptr) int32

func (self *Connection) Execute(statement string, params []ParameterValue) witTypes.Result[witTypes.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	params0 := witRuntime.Allocate(pinner, (5 * 4), 4)
	*(*int32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 0)), 0)) = (self).Handle()
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 4)), 4)) = uint32(uint32(len(statement)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), 4)), 0)) = uint32(uintptr(uintptr(utf8)))
	slice := params
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(8+2*4))

		switch element.Tag() {
		case ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

		case ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), (3*4))), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.Add(unsafe.Pointer(params0), (3*4))), 0)) = uint32(uintptr(uintptr(result2)))

	witAsync.SubtaskWait(uint32(wasm_import_method_connection_execute(uintptr(params0), returnArea)))
	var result7 witTypes.Result[witTypes.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result7 = witTypes.Ok[witTypes.Unit, Error](witTypes.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 1:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorBadParameter(value3)

		case 2:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorQueryFailed(value4)

		case 3:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorValueConversionFailed(value5)

		case 4:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value6)

		default:
			panic("unreachable")
		}

		result7 = witTypes.Err[witTypes.Unit, Error](variant)
	default:
		panic("unreachable")
	}

	return result7

}
