// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_sockets_0_2_6_network

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
)

//go:wasmimport wasi:sockets/network@0.2.6 [resource-drop]network
func resourceDropNetwork(handle int32)

// An opaque resource that represents access to (a subset of) the network.
// This enables context-based security for networking.
// There is no need for this to map 1:1 to a physical network interface.
type Network struct {
	handle *witRuntime.Handle
}

func (self *Network) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Network) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Network) Handle() int32 {
	return self.handle.Use()
}

func (self *Network) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropNetwork(handle)
	}
}

func NetworkFromOwnHandle(handleValue int32) *Network {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Network{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropNetwork(handleValue)
		}
	}, 0)
	return value
}

func NetworkFromBorrowHandle(handleValue int32) *Network {
	handle := witRuntime.MakeHandle(handleValue)
	return &Network{handle}
}

const (
	// Unknown error
	ErrorCodeUnknown uint8 = 0
	// Access denied.
	//
	// POSIX equivalent: EACCES, EPERM
	ErrorCodeAccessDenied uint8 = 1
	// The operation is not supported.
	//
	// POSIX equivalent: EOPNOTSUPP
	ErrorCodeNotSupported uint8 = 2
	// One of the arguments is invalid.
	//
	// POSIX equivalent: EINVAL
	ErrorCodeInvalidArgument uint8 = 3
	// Not enough memory to complete the operation.
	//
	// POSIX equivalent: ENOMEM, ENOBUFS, EAI_MEMORY
	ErrorCodeOutOfMemory uint8 = 4
	// The operation timed out before it could finish completely.
	ErrorCodeTimeout uint8 = 5
	// This operation is incompatible with another asynchronous operation that is already in progress.
	//
	// POSIX equivalent: EALREADY
	ErrorCodeConcurrencyConflict uint8 = 6
	// Trying to finish an asynchronous operation that:
	// - has not been started yet, or:
	// - was already finished by a previous `finish-*` call.
	//
	// Note: this is scheduled to be removed when `future`s are natively supported.
	ErrorCodeNotInProgress uint8 = 7
	// The operation has been aborted because it could not be completed immediately.
	//
	// Note: this is scheduled to be removed when `future`s are natively supported.
	ErrorCodeWouldBlock uint8 = 8
	// The operation is not valid in the socket's current state.
	ErrorCodeInvalidState uint8 = 9
	// A new socket resource could not be created because of a system limit.
	ErrorCodeNewSocketLimit uint8 = 10
	// A bind operation failed because the provided address is not an address that the `network` can bind to.
	ErrorCodeAddressNotBindable uint8 = 11
	// A bind operation failed because the provided address is already in use or because there are no ephemeral ports available.
	ErrorCodeAddressInUse uint8 = 12
	// The remote address is not reachable
	ErrorCodeRemoteUnreachable uint8 = 13
	// The TCP connection was forcefully rejected
	ErrorCodeConnectionRefused uint8 = 14
	// The TCP connection was reset.
	ErrorCodeConnectionReset uint8 = 15
	// A TCP connection was aborted.
	ErrorCodeConnectionAborted uint8 = 16
	// The size of a datagram sent to a UDP socket exceeded the maximum
	// supported size.
	ErrorCodeDatagramTooLarge uint8 = 17
	// Name does not exist or has no suitable associated IP addresses.
	ErrorCodeNameUnresolvable uint8 = 18
	// A temporary failure in name resolution occurred.
	ErrorCodeTemporaryResolverFailure uint8 = 19
	// A permanent failure in name resolution occurred.
	ErrorCodePermanentResolverFailure uint8 = 20
)

// Error codes.
//
// In theory, every API can return any error code.
// In practice, API's typically only return the errors documented per API
// combined with a couple of errors that are always possible:
// - `unknown`
// - `access-denied`
// - `not-supported`
// - `out-of-memory`
// - `concurrency-conflict`
//
// See each individual API for what the POSIX equivalents are. They sometimes differ per API.
type ErrorCode = uint8

const (
	// Similar to `AF_INET` in POSIX.
	IpAddressFamilyIpv4 uint8 = 0
	// Similar to `AF_INET6` in POSIX.
	IpAddressFamilyIpv6 uint8 = 1
)

type IpAddressFamily = uint8
type Ipv4Address = witTypes.Tuple4[uint8, uint8, uint8, uint8]
type Ipv6Address = witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]

const (
	IpAddressIpv4 uint8 = 0
	IpAddressIpv6 uint8 = 1
)

type IpAddress struct {
	tag   uint8
	value any
}

func (self IpAddress) Tag() uint8 {
	return self.tag
}

func (self IpAddress) Ipv4() witTypes.Tuple4[uint8, uint8, uint8, uint8] {
	if self.tag != IpAddressIpv4 {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple4[uint8, uint8, uint8, uint8])
}
func (self IpAddress) Ipv6() witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16] {
	if self.tag != IpAddressIpv6 {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16])
}

func MakeIpAddressIpv4(value witTypes.Tuple4[uint8, uint8, uint8, uint8]) IpAddress {
	return IpAddress{IpAddressIpv4, value}
}
func MakeIpAddressIpv6(value witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]) IpAddress {
	return IpAddress{IpAddressIpv6, value}
}

type Ipv4SocketAddress struct {
	// sin_port
	Port uint16
	// sin_addr
	Address witTypes.Tuple4[uint8, uint8, uint8, uint8]
}

type Ipv6SocketAddress struct {
	// sin6_port
	Port uint16
	// sin6_flowinfo
	FlowInfo uint32
	// sin6_addr
	Address witTypes.Tuple8[uint16, uint16, uint16, uint16, uint16, uint16, uint16, uint16]
	// sin6_scope_id
	ScopeId uint32
}

const (
	IpSocketAddressIpv4 uint8 = 0
	IpSocketAddressIpv6 uint8 = 1
)

type IpSocketAddress struct {
	tag   uint8
	value any
}

func (self IpSocketAddress) Tag() uint8 {
	return self.tag
}

func (self IpSocketAddress) Ipv4() Ipv4SocketAddress {
	if self.tag != IpSocketAddressIpv4 {
		panic("tag mismatch")
	}
	return self.value.(Ipv4SocketAddress)
}
func (self IpSocketAddress) Ipv6() Ipv6SocketAddress {
	if self.tag != IpSocketAddressIpv6 {
		panic("tag mismatch")
	}
	return self.value.(Ipv6SocketAddress)
}

func MakeIpSocketAddressIpv4(value Ipv4SocketAddress) IpSocketAddress {
	return IpSocketAddress{IpSocketAddressIpv4, value}
}
func MakeIpSocketAddressIpv6(value Ipv6SocketAddress) IpSocketAddress {
	return IpSocketAddress{IpSocketAddressIpv6, value}
}
