// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package spin_postgres_postgres

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

const (
	ErrorConnectionFailed      uint8 = 0
	ErrorBadParameter          uint8 = 1
	ErrorQueryFailed           uint8 = 2
	ErrorValueConversionFailed uint8 = 3
	ErrorOther                 uint8 = 4
)

// Errors related to interacting with a database.
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) ConnectionFailed() string {
	if self.tag != ErrorConnectionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) BadParameter() string {
	if self.tag != ErrorBadParameter {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) QueryFailed() string {
	if self.tag != ErrorQueryFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) ValueConversionFailed() string {
	if self.tag != ErrorValueConversionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorConnectionFailed(value string) Error {
	return Error{ErrorConnectionFailed, value}
}
func MakeErrorBadParameter(value string) Error {
	return Error{ErrorBadParameter, value}
}
func MakeErrorQueryFailed(value string) Error {
	return Error{ErrorQueryFailed, value}
}
func MakeErrorValueConversionFailed(value string) Error {
	return Error{ErrorValueConversionFailed, value}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

const (
	DbDataTypeBoolean    uint8 = 0
	DbDataTypeInt8       uint8 = 1
	DbDataTypeInt16      uint8 = 2
	DbDataTypeInt32      uint8 = 3
	DbDataTypeInt64      uint8 = 4
	DbDataTypeFloating32 uint8 = 5
	DbDataTypeFloating64 uint8 = 6
	DbDataTypeStr        uint8 = 7
	DbDataTypeBinary     uint8 = 8
	DbDataTypeDate       uint8 = 9
	DbDataTypeTime       uint8 = 10
	DbDataTypeDatetime   uint8 = 11
	DbDataTypeTimestamp  uint8 = 12
	DbDataTypeOther      uint8 = 13
)

// Data types for a database column
type DbDataType = uint8

const (
	DbValueBoolean    uint8 = 0
	DbValueInt8       uint8 = 1
	DbValueInt16      uint8 = 2
	DbValueInt32      uint8 = 3
	DbValueInt64      uint8 = 4
	DbValueFloating32 uint8 = 5
	DbValueFloating64 uint8 = 6
	DbValueStr        uint8 = 7
	DbValueBinary     uint8 = 8
	DbValueDate       uint8 = 9
	// (year, month, day)
	DbValueTime uint8 = 10
	// (hour, minute, second, nanosecond)
	// Date-time types are always treated as UTC (without timezone info).
	// The instant is represented as a (year, month, day, hour, minute, second, nanosecond) tuple.
	DbValueDatetime uint8 = 11
	// Unix timestamp (seconds since epoch)
	DbValueTimestamp   uint8 = 12
	DbValueDbNull      uint8 = 13
	DbValueUnsupported uint8 = 14
)

// Database values
type DbValue struct {
	tag   uint8
	value any
}

func (self DbValue) Tag() uint8 {
	return self.tag
}

func (self DbValue) Boolean() bool {
	if self.tag != DbValueBoolean {
		panic("tag mismatch")
	}
	return self.value.(bool)
}
func (self DbValue) Int8() int8 {
	if self.tag != DbValueInt8 {
		panic("tag mismatch")
	}
	return self.value.(int8)
}
func (self DbValue) Int16() int16 {
	if self.tag != DbValueInt16 {
		panic("tag mismatch")
	}
	return self.value.(int16)
}
func (self DbValue) Int32() int32 {
	if self.tag != DbValueInt32 {
		panic("tag mismatch")
	}
	return self.value.(int32)
}
func (self DbValue) Int64() int64 {
	if self.tag != DbValueInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self DbValue) Floating32() float32 {
	if self.tag != DbValueFloating32 {
		panic("tag mismatch")
	}
	return self.value.(float32)
}
func (self DbValue) Floating64() float64 {
	if self.tag != DbValueFloating64 {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self DbValue) Str() string {
	if self.tag != DbValueStr {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self DbValue) Binary() []uint8 {
	if self.tag != DbValueBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}
func (self DbValue) Date() witTypes.Tuple3[int32, uint8, uint8] {
	if self.tag != DbValueDate {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple3[int32, uint8, uint8])
}
func (self DbValue) Time() witTypes.Tuple4[uint8, uint8, uint8, uint32] {
	if self.tag != DbValueTime {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple4[uint8, uint8, uint8, uint32])
}
func (self DbValue) Datetime() witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
	if self.tag != DbValueDatetime {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32])
}
func (self DbValue) Timestamp() int64 {
	if self.tag != DbValueTimestamp {
		panic("tag mismatch")
	}
	return self.value.(int64)
}

func MakeDbValueBoolean(value bool) DbValue {
	return DbValue{DbValueBoolean, value}
}
func MakeDbValueInt8(value int8) DbValue {
	return DbValue{DbValueInt8, value}
}
func MakeDbValueInt16(value int16) DbValue {
	return DbValue{DbValueInt16, value}
}
func MakeDbValueInt32(value int32) DbValue {
	return DbValue{DbValueInt32, value}
}
func MakeDbValueInt64(value int64) DbValue {
	return DbValue{DbValueInt64, value}
}
func MakeDbValueFloating32(value float32) DbValue {
	return DbValue{DbValueFloating32, value}
}
func MakeDbValueFloating64(value float64) DbValue {
	return DbValue{DbValueFloating64, value}
}
func MakeDbValueStr(value string) DbValue {
	return DbValue{DbValueStr, value}
}
func MakeDbValueBinary(value []uint8) DbValue {
	return DbValue{DbValueBinary, value}
}
func MakeDbValueDate(value witTypes.Tuple3[int32, uint8, uint8]) DbValue {
	return DbValue{DbValueDate, value}
}
func MakeDbValueTime(value witTypes.Tuple4[uint8, uint8, uint8, uint32]) DbValue {
	return DbValue{DbValueTime, value}
}
func MakeDbValueDatetime(value witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) DbValue {
	return DbValue{DbValueDatetime, value}
}
func MakeDbValueTimestamp(value int64) DbValue {
	return DbValue{DbValueTimestamp, value}
}
func MakeDbValueDbNull() DbValue {
	return DbValue{DbValueDbNull, nil}
}
func MakeDbValueUnsupported() DbValue {
	return DbValue{DbValueUnsupported, nil}
}

const (
	ParameterValueBoolean    uint8 = 0
	ParameterValueInt8       uint8 = 1
	ParameterValueInt16      uint8 = 2
	ParameterValueInt32      uint8 = 3
	ParameterValueInt64      uint8 = 4
	ParameterValueFloating32 uint8 = 5
	ParameterValueFloating64 uint8 = 6
	ParameterValueStr        uint8 = 7
	ParameterValueBinary     uint8 = 8
	ParameterValueDate       uint8 = 9
	// (year, month, day)
	ParameterValueTime uint8 = 10
	// (hour, minute, second, nanosecond)
	// Date-time types are always treated as UTC (without timezone info).
	// The instant is represented as a (year, month, day, hour, minute, second, nanosecond) tuple.
	ParameterValueDatetime uint8 = 11
	// Unix timestamp (seconds since epoch)
	ParameterValueTimestamp uint8 = 12
	ParameterValueDbNull    uint8 = 13
)

// Values used in parameterized queries
type ParameterValue struct {
	tag   uint8
	value any
}

func (self ParameterValue) Tag() uint8 {
	return self.tag
}

func (self ParameterValue) Boolean() bool {
	if self.tag != ParameterValueBoolean {
		panic("tag mismatch")
	}
	return self.value.(bool)
}
func (self ParameterValue) Int8() int8 {
	if self.tag != ParameterValueInt8 {
		panic("tag mismatch")
	}
	return self.value.(int8)
}
func (self ParameterValue) Int16() int16 {
	if self.tag != ParameterValueInt16 {
		panic("tag mismatch")
	}
	return self.value.(int16)
}
func (self ParameterValue) Int32() int32 {
	if self.tag != ParameterValueInt32 {
		panic("tag mismatch")
	}
	return self.value.(int32)
}
func (self ParameterValue) Int64() int64 {
	if self.tag != ParameterValueInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self ParameterValue) Floating32() float32 {
	if self.tag != ParameterValueFloating32 {
		panic("tag mismatch")
	}
	return self.value.(float32)
}
func (self ParameterValue) Floating64() float64 {
	if self.tag != ParameterValueFloating64 {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self ParameterValue) Str() string {
	if self.tag != ParameterValueStr {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self ParameterValue) Binary() []uint8 {
	if self.tag != ParameterValueBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}
func (self ParameterValue) Date() witTypes.Tuple3[int32, uint8, uint8] {
	if self.tag != ParameterValueDate {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple3[int32, uint8, uint8])
}
func (self ParameterValue) Time() witTypes.Tuple4[uint8, uint8, uint8, uint32] {
	if self.tag != ParameterValueTime {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple4[uint8, uint8, uint8, uint32])
}
func (self ParameterValue) Datetime() witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32] {
	if self.tag != ParameterValueDatetime {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32])
}
func (self ParameterValue) Timestamp() int64 {
	if self.tag != ParameterValueTimestamp {
		panic("tag mismatch")
	}
	return self.value.(int64)
}

func MakeParameterValueBoolean(value bool) ParameterValue {
	return ParameterValue{ParameterValueBoolean, value}
}
func MakeParameterValueInt8(value int8) ParameterValue {
	return ParameterValue{ParameterValueInt8, value}
}
func MakeParameterValueInt16(value int16) ParameterValue {
	return ParameterValue{ParameterValueInt16, value}
}
func MakeParameterValueInt32(value int32) ParameterValue {
	return ParameterValue{ParameterValueInt32, value}
}
func MakeParameterValueInt64(value int64) ParameterValue {
	return ParameterValue{ParameterValueInt64, value}
}
func MakeParameterValueFloating32(value float32) ParameterValue {
	return ParameterValue{ParameterValueFloating32, value}
}
func MakeParameterValueFloating64(value float64) ParameterValue {
	return ParameterValue{ParameterValueFloating64, value}
}
func MakeParameterValueStr(value string) ParameterValue {
	return ParameterValue{ParameterValueStr, value}
}
func MakeParameterValueBinary(value []uint8) ParameterValue {
	return ParameterValue{ParameterValueBinary, value}
}
func MakeParameterValueDate(value witTypes.Tuple3[int32, uint8, uint8]) ParameterValue {
	return ParameterValue{ParameterValueDate, value}
}
func MakeParameterValueTime(value witTypes.Tuple4[uint8, uint8, uint8, uint32]) ParameterValue {
	return ParameterValue{ParameterValueTime, value}
}
func MakeParameterValueDatetime(value witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]) ParameterValue {
	return ParameterValue{ParameterValueDatetime, value}
}
func MakeParameterValueTimestamp(value int64) ParameterValue {
	return ParameterValue{ParameterValueTimestamp, value}
}
func MakeParameterValueDbNull() ParameterValue {
	return ParameterValue{ParameterValueDbNull, nil}
}

// A database column
type Column struct {
	Name     string
	DataType DbDataType
}

// A database row
type Row = []DbValue

// A set of database rows
type RowSet struct {
	Columns []Column
	Rows    [][]DbValue
}

//go:wasmimport spin:postgres/postgres@3.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A connection to a postgres database.
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

//go:wasmimport spin:postgres/postgres@3.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func ConnectionOpen(address string) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), returnArea)
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorConnectionFailed(value)

		case 1:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorBadParameter(value0)

		case 2:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorQueryFailed(value1)

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorValueConversionFailed(value2)

		case 4:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value3)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}
	result4 := result
	return result4

}

//go:wasmimport spin:postgres/postgres@3.0.0 [method]connection.query
func wasm_import_method_connection_query(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Query(statement string, params []ParameterValue) witTypes.Result[RowSet, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := params
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*24), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*24)

		switch element.Tag() {
		case ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ParameterValueDate:
			payload := element.Date()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))

		case ParameterValueTime:
			payload := element.Time()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32((payload).F0))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((payload).F2))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F3)

		case ParameterValueDatetime:
			payload := element.Datetime()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 14)) = int8(int32((payload).F3))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 15)) = int8(int32((payload).F4))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F5))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F6)

		case ParameterValueTimestamp:
			payload := element.Timestamp()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_query((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result1), length, returnArea)
	var result13 witTypes.Result[RowSet, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result2 := make([]Column, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(3*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result2 = append(result2, Column{value, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))})
		}

		result6 := make([][]DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(2*4))
			result5 := make([]DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*24)
				var variant DbValue
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
				case 0:

					variant = MakeDbValueBoolean((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

				case 1:

					variant = MakeDbValueInt8(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 2:

					variant = MakeDbValueInt16(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 3:

					variant = MakeDbValueInt32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 4:

					variant = MakeDbValueInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 5:

					variant = MakeDbValueFloating32(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 6:

					variant = MakeDbValueFloating64(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 7:
					value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeDbValueStr(value3)

				case 8:
					value4 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeDbValueBinary(value4)

				case 9:

					variant = MakeDbValueDate(witTypes.Tuple3[int32, uint8, uint8]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 13))))})

				case 10:

					variant = MakeDbValueTime(witTypes.Tuple4[uint8, uint8, uint8, uint32]{uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 9)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 10)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)))})

				case 11:

					variant = MakeDbValueDatetime(witTypes.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]{*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 12)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 13)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 14)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 15)))), uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)))})

				case 12:

					variant = MakeDbValueTimestamp(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 13:

					variant = MakeDbValueDbNull()

				case 14:

					variant = MakeDbValueUnsupported()

				default:
					panic("unreachable")
				}

				result5 = append(result5, variant)
			}

			result6 = append(result6, result5)
		}

		result13 = witTypes.Ok[RowSet, Error](RowSet{result2, result6})
	case 1:
		var variant12 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = MakeErrorConnectionFailed(value7)

		case 1:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = MakeErrorBadParameter(value8)

		case 2:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = MakeErrorQueryFailed(value9)

		case 3:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = MakeErrorValueConversionFailed(value10)

		case 4:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant12 = MakeErrorOther(value11)

		default:
			panic("unreachable")
		}

		result13 = witTypes.Err[RowSet, Error](variant12)
	default:
		panic("unreachable")
	}
	result14 := result13
	return result14

}

//go:wasmimport spin:postgres/postgres@3.0.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Execute(statement string, params []ParameterValue) witTypes.Result[uint64, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := params
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*24), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*24)

		switch element.Tag() {
		case ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ParameterValueDate:
			payload := element.Date()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))

		case ParameterValueTime:
			payload := element.Time()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32((payload).F0))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 9)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 10)) = int8(int32((payload).F2))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 12)) = int32((payload).F3)

		case ParameterValueDatetime:
			payload := element.Datetime()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = (payload).F0
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 12)) = int8(int32((payload).F1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 13)) = int8(int32((payload).F2))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 14)) = int8(int32((payload).F3))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 15)) = int8(int32((payload).F4))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(int32((payload).F5))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 20)) = int32((payload).F6)

		case ParameterValueTimestamp:
			payload := element.Timestamp()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result1), length, returnArea)
	var result6 witTypes.Result[uint64, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result6 = witTypes.Ok[uint64, Error](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorConnectionFailed(value)

		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorBadParameter(value2)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorQueryFailed(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorValueConversionFailed(value4)

		case 4:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorOther(value5)

		default:
			panic("unreachable")
		}

		result6 = witTypes.Err[uint64, Error](variant)
	default:
		panic("unreachable")
	}
	result7 := result6
	return result7

}
