spin_manifest_version = 2

[application]
name = "sqlite-example"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "sqlite"

[component.sqlite]
source = "main.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]
[component.sqlite.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/spinframework/spin-go-sdk/v3)/wit --wit-world http-trigger -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
