// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_io_0_2_0_streams

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_io_0_2_0_error"
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_io_0_2_0_poll"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Error = wasi_io_0_2_0_error.Error
type Pollable = wasi_io_0_2_0_poll.Pollable

const (
	// The last operation (a write or flush) failed before completion.
	//
	// More information is available in the `error` payload.
	StreamErrorLastOperationFailed uint8 = 0
	// The stream is closed: no more input will be accepted by the
	// stream. A closed output-stream will return this error on all
	// future operations.
	StreamErrorClosed uint8 = 1
)

// An error for input-stream and output-stream operations.
type StreamError struct {
	tag   uint8
	value any
}

func (self StreamError) Tag() uint8 {
	return self.tag
}

func (self StreamError) LastOperationFailed() *wasi_io_0_2_0_error.Error {
	if self.tag != StreamErrorLastOperationFailed {
		panic("tag mismatch")
	}
	return self.value.(*wasi_io_0_2_0_error.Error)
}

func MakeStreamErrorLastOperationFailed(value *wasi_io_0_2_0_error.Error) StreamError {
	return StreamError{StreamErrorLastOperationFailed, value}
}
func MakeStreamErrorClosed() StreamError {
	return StreamError{StreamErrorClosed, nil}
}

//go:wasmimport wasi:io/streams@0.2.0 [resource-drop]input-stream
func resourceDropInputStream(handle int32)

// An input bytestream.
//
// `input-stream`s are *non-blocking* to the extent practical on underlying
// platforms. I/O operations always return promptly; if fewer bytes are
// promptly available than requested, they return the number of bytes promptly
// available, which could even be zero. To wait for data to be available,
// use the `subscribe` function to obtain a `pollable` which can be polled
// for using `wasi:io/poll`.
type InputStream struct {
	handle *witRuntime.Handle
}

func (self *InputStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *InputStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *InputStream) Handle() int32 {
	return self.handle.Use()
}

func (self *InputStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropInputStream(handle)
	}
}

func InputStreamFromOwnHandle(handleValue int32) *InputStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &InputStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropInputStream(handleValue)
		}
	}, 0)
	return value
}

func InputStreamFromBorrowHandle(handleValue int32) *InputStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &InputStream{handle}
}

//go:wasmimport wasi:io/streams@0.2.0 [resource-drop]output-stream
func resourceDropOutputStream(handle int32)

// An output bytestream.
//
// `output-stream`s are *non-blocking* to the extent practical on
// underlying platforms. Except where specified otherwise, I/O operations also
// always return promptly, after the number of bytes that can be written
// promptly, which could even be zero. To wait for the stream to be ready to
// accept data, the `subscribe` function to obtain a `pollable` which can be
// polled for using `wasi:io/poll`.
type OutputStream struct {
	handle *witRuntime.Handle
}

func (self *OutputStream) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *OutputStream) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *OutputStream) Handle() int32 {
	return self.handle.Use()
}

func (self *OutputStream) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropOutputStream(handle)
	}
}

func OutputStreamFromOwnHandle(handleValue int32) *OutputStream {
	handle := witRuntime.MakeHandle(handleValue)
	value := &OutputStream{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropOutputStream(handleValue)
		}
	}, 0)
	return value
}

func OutputStreamFromBorrowHandle(handleValue int32) *OutputStream {
	handle := witRuntime.MakeHandle(handleValue)
	return &OutputStream{handle}
}

//go:wasmimport wasi:io/streams@0.2.0 [method]input-stream.read
func wasm_import_method_input_stream_read(arg0 int32, arg1 int64, arg2 uintptr)

func (self *InputStream) Read(len uint64) witTypes.Result[[]uint8, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_input_stream_read((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[[]uint8, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, StreamError](value)
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 1*4)))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]input-stream.blocking-read
func wasm_import_method_input_stream_blocking_read(arg0 int32, arg1 int64, arg2 uintptr)

func (self *InputStream) BlockingRead(len uint64) witTypes.Result[[]uint8, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	wasm_import_method_input_stream_blocking_read((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[[]uint8, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result = witTypes.Ok[[]uint8, StreamError](value)
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (4 + 1*4)))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[[]uint8, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]input-stream.skip
func wasm_import_method_input_stream_skip(arg0 int32, arg1 int64, arg2 uintptr)

func (self *InputStream) Skip(len uint64) witTypes.Result[uint64, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_method_input_stream_skip((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[uint64, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, StreamError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]input-stream.blocking-skip
func wasm_import_method_input_stream_blocking_skip(arg0 int32, arg1 int64, arg2 uintptr)

func (self *InputStream) BlockingSkip(len uint64) witTypes.Result[uint64, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_method_input_stream_blocking_skip((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[uint64, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, StreamError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]input-stream.subscribe
func wasm_import_method_input_stream_subscribe(arg0 int32) int32

func (self *InputStream) Subscribe() *wasi_io_0_2_0_poll.Pollable {

	result := wasm_import_method_input_stream_subscribe((self).Handle())
	return wasi_io_0_2_0_poll.PollableFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.check-write
func wasm_import_method_output_stream_check_write(arg0 int32, arg1 uintptr)

func (self *OutputStream) CheckWrite() witTypes.Result[uint64, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_method_output_stream_check_write((self).Handle(), returnArea)
	var result witTypes.Result[uint64, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, StreamError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.write
func wasm_import_method_output_stream_write(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *OutputStream) Write(contents []uint8) witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	data := unsafe.Pointer(unsafe.SliceData(contents))
	pinner.Pin(data)
	wasm_import_method_output_stream_write((self).Handle(), uintptr(data), uint32(len(contents)), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.blocking-write-and-flush
func wasm_import_method_output_stream_blocking_write_and_flush(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *OutputStream) BlockingWriteAndFlush(contents []uint8) witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	data := unsafe.Pointer(unsafe.SliceData(contents))
	pinner.Pin(data)
	wasm_import_method_output_stream_blocking_write_and_flush((self).Handle(), uintptr(data), uint32(len(contents)), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.flush
func wasm_import_method_output_stream_flush(arg0 int32, arg1 uintptr)

func (self *OutputStream) Flush() witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	wasm_import_method_output_stream_flush((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.blocking-flush
func wasm_import_method_output_stream_blocking_flush(arg0 int32, arg1 uintptr)

func (self *OutputStream) BlockingFlush() witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	wasm_import_method_output_stream_blocking_flush((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.subscribe
func wasm_import_method_output_stream_subscribe(arg0 int32) int32

func (self *OutputStream) Subscribe() *wasi_io_0_2_0_poll.Pollable {

	result := wasm_import_method_output_stream_subscribe((self).Handle())
	return wasi_io_0_2_0_poll.PollableFromOwnHandle(int32(uintptr(result)))

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.write-zeroes
func wasm_import_method_output_stream_write_zeroes(arg0 int32, arg1 int64, arg2 uintptr)

func (self *OutputStream) WriteZeroes(len uint64) witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	wasm_import_method_output_stream_write_zeroes((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.blocking-write-zeroes-and-flush
func wasm_import_method_output_stream_blocking_write_zeroes_and_flush(arg0 int32, arg1 int64, arg2 uintptr)

func (self *OutputStream) BlockingWriteZeroesAndFlush(len uint64) witTypes.Result[witTypes.Unit, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 12, 4))
	wasm_import_method_output_stream_blocking_write_zeroes_and_flush((self).Handle(), int64(len), returnArea)
	var result witTypes.Result[witTypes.Unit, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, StreamError](witTypes.Unit{})
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 8))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.splice
func wasm_import_method_output_stream_splice(arg0 int32, arg1 int32, arg2 int64, arg3 uintptr)

func (self *OutputStream) Splice(src *InputStream, len uint64) witTypes.Result[uint64, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_method_output_stream_splice((self).Handle(), (src).Handle(), int64(len), returnArea)
	var result witTypes.Result[uint64, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, StreamError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:io/streams@0.2.0 [method]output-stream.blocking-splice
func wasm_import_method_output_stream_blocking_splice(arg0 int32, arg1 int32, arg2 int64, arg3 uintptr)

func (self *OutputStream) BlockingSplice(src *InputStream, len uint64) witTypes.Result[uint64, StreamError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 16, 8))
	wasm_import_method_output_stream_blocking_splice((self).Handle(), (src).Handle(), int64(len), returnArea)
	var result witTypes.Result[uint64, StreamError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[uint64, StreamError](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8))))
	case 1:
		var variant StreamError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeStreamErrorLastOperationFailed(wasi_io_0_2_0_error.ErrorFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 12))))))

		case 1:

			variant = MakeStreamErrorClosed()

		default:
			panic("unreachable")
		}

		result = witTypes.Err[uint64, StreamError](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}
