// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     spin:key-value@3.0.0
//     spin:mqtt@3.0.0
//     spin:postgres@4.0.0
//     spin:postgres@4.1.0
//     spin:postgres@4.2.0
//     spin:redis@3.0.0
//     spin:sqlite@3.0.0
//     spin:sqlite@3.1.0
//     wasi:io@0.2.3
//     wasi:clocks@0.2.3
//     wasi:filesystem@0.2.3
//     wasi:sockets@0.2.3
//     wasi:random@0.2.3
//     wasi:cli@0.2.3
//     wasi:http@0.2.3
//     spin:up@3.2.0
//     spin:up@3.4.0
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.3.0-rc-2026-03-15
//     wasi:io@0.2.6
//     wasi:clocks@0.2.6
//     wasi:filesystem@0.2.6
//     wasi:sockets@0.2.6
//     wasi:random@0.2.6
//     wasi:cli@0.2.6
//     wasi:otel@0.2.0-rc.2
//     wasi:http@0.2.6
//     spin:variables@3.0.0
//     spin:up@4.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10
//     componentize-go:union

package wasi_keyvalue_0_2_0_draft2_atomics

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/wasi_keyvalue_0_2_0_draft2_store"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Bucket = wasi_keyvalue_0_2_0_draft2_store.Bucket
type Error = wasi_keyvalue_0_2_0_draft2_store.Error

//go:wasmimport wasi:keyvalue/atomics@0.2.0-draft2 [resource-drop]cas
func resourceDropCas(handle int32)

// A handle to a CAS (compare-and-swap) operation.
type Cas struct {
	handle *witRuntime.Handle
}

func (self *Cas) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Cas) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Cas) Handle() int32 {
	return self.handle.Use()
}

func (self *Cas) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropCas(handle)
	}
}

func CasFromOwnHandle(handleValue int32) *Cas {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Cas{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropCas(handleValue)
		}
	}, 0)
	return value
}

func CasFromBorrowHandle(handleValue int32) *Cas {
	handle := witRuntime.MakeHandle(handleValue)
	return &Cas{handle}
}

const (
	// A store error occurred when performing the operation
	CasErrorStoreError uint8 = 0
	// The CAS operation failed because the value was too old. This returns a new CAS handle
	// for easy retries. Implementors MUST return a CAS handle that has been updated to the
	// latest version or transaction.
	CasErrorCasFailed uint8 = 1
)

// The error returned by a CAS operation
type CasError struct {
	tag   uint8
	value any
}

func (self CasError) Tag() uint8 {
	return self.tag
}

func (self CasError) StoreError() wasi_keyvalue_0_2_0_draft2_store.Error {
	if self.tag != CasErrorStoreError {
		panic("tag mismatch")
	}
	return self.value.(wasi_keyvalue_0_2_0_draft2_store.Error)
}
func (self CasError) CasFailed() *Cas {
	if self.tag != CasErrorCasFailed {
		panic("tag mismatch")
	}
	return self.value.(*Cas)
}

func MakeCasErrorStoreError(value wasi_keyvalue_0_2_0_draft2_store.Error) CasError {
	return CasError{CasErrorStoreError, value}
}
func MakeCasErrorCasFailed(value *Cas) CasError {
	return CasError{CasErrorCasFailed, value}
}

//go:wasmimport wasi:keyvalue/atomics@0.2.0-draft2 [static]cas.new
func wasm_import_static_cas_new(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func CasNew(bucket *wasi_keyvalue_0_2_0_draft2_store.Bucket, key string) witTypes.Result[*Cas, wasi_keyvalue_0_2_0_draft2_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_static_cas_new((bucket).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result witTypes.Result[*Cas, wasi_keyvalue_0_2_0_draft2_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Cas, wasi_keyvalue_0_2_0_draft2_store.Error](CasFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant wasi_keyvalue_0_2_0_draft2_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Cas, wasi_keyvalue_0_2_0_draft2_store.Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:keyvalue/atomics@0.2.0-draft2 [method]cas.current
func wasm_import_method_cas_current(arg0 int32, arg1 uintptr)

func (self *Cas) Current() witTypes.Result[witTypes.Option[[]uint8], wasi_keyvalue_0_2_0_draft2_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	wasm_import_method_cas_current((self).Handle(), returnArea)
	var result witTypes.Result[witTypes.Option[[]uint8], wasi_keyvalue_0_2_0_draft2_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option witTypes.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = witTypes.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			option = witTypes.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = witTypes.Ok[witTypes.Option[[]uint8], wasi_keyvalue_0_2_0_draft2_store.Error](option)
	case 1:
		var variant wasi_keyvalue_0_2_0_draft2_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorAccessDenied()

		case 2:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Option[[]uint8], wasi_keyvalue_0_2_0_draft2_store.Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:keyvalue/atomics@0.2.0-draft2 increment
func wasm_import_increment(arg0 int32, arg1 uintptr, arg2 uint32, arg3 int64, arg4 uintptr)

func Increment(bucket *wasi_keyvalue_0_2_0_draft2_store.Bucket, key string, delta int64) witTypes.Result[int64, wasi_keyvalue_0_2_0_draft2_store.Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_increment((bucket).Handle(), uintptr(utf8), uint32(len(key)), delta, returnArea)
	var result witTypes.Result[int64, wasi_keyvalue_0_2_0_draft2_store.Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[int64, wasi_keyvalue_0_2_0_draft2_store.Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:
		var variant wasi_keyvalue_0_2_0_draft2_store.Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorNoSuchStore()

		case 1:

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[int64, wasi_keyvalue_0_2_0_draft2_store.Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:keyvalue/atomics@0.2.0-draft2 swap
func wasm_import_swap(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func Swap(cas *Cas, value []uint8) witTypes.Result[witTypes.Unit, CasError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_swap((cas).TakeHandle(), uintptr(data), uint32(len(value)), returnArea)
	var result witTypes.Result[witTypes.Unit, CasError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[witTypes.Unit, CasError](witTypes.Unit{})
	case 1:
		var variant1 CasError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:
			var variant wasi_keyvalue_0_2_0_draft2_store.Error
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))) {
			case 0:

				variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorNoSuchStore()

			case 1:

				variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorAccessDenied()

			case 2:
				value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))

				variant = wasi_keyvalue_0_2_0_draft2_store.MakeErrorOther(value0)

			default:
				panic("unreachable")
			}

			variant1 = MakeCasErrorStoreError(variant)

		case 1:

			variant1 = MakeCasErrorCasFailed(CasFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))))

		default:
			panic("unreachable")
		}

		result = witTypes.Err[witTypes.Unit, CasError](variant1)
	default:
		panic("unreachable")
	}
	result2 := result
	return result2

}
