spin_manifest_version = 2

[application]
name = "go-redis-outbound-example"
version = "0.1.0"
authors = ["Andrew Steurer <94206073+asteurer@users.noreply.github.com>"]
description = "Using Spin with Redis"

[[trigger.http]]
route = "/"
component = "redis-outbound"

[component.redis-outbound]
source = "main.wasm"
environment = { REDIS_ADDRESS = "redis://localhost:6379", REDIS_CHANNEL = "messages" }
allowed_outbound_hosts = ["redis://localhost:6379"]

[component.redis-outbound.build]
# Note that we specify both `spin:up/http-trigger@4.0.0` _and_
# `spin:up/redis-trigger@4.0.0` here, even though we only really want the
# former.  That's because, as of this writing the `redis` package in
# `spin-go-sdk` covers both inbound and outbound Redis APIs and thus pulls in
# imports for both.  In order for `componentize-go` to resolve those imports, we
# need to specify both worlds here.
command = "go tool componentize-go -w spin:up/http-trigger@4.0.0 -w spin:up/redis-trigger@4.0.0 build"
watch = ["**/*.go", "go.mod"]
