// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package fermyon_spin_redis_types

import ()

const (
	ErrorSuccess uint8 = 0
	ErrorError   uint8 = 1
)

// General purpose error.
type Error = uint8

// The message payload.
type Payload = []uint8

const (
	RedisParameterInt64  uint8 = 0
	RedisParameterBinary uint8 = 1
)

// A parameter type for the general-purpose `execute` function.
type RedisParameter struct {
	tag   uint8
	value any
}

func (self RedisParameter) Tag() uint8 {
	return self.tag
}

func (self RedisParameter) Int64() int64 {
	if self.tag != RedisParameterInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self RedisParameter) Binary() []uint8 {
	if self.tag != RedisParameterBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeRedisParameterInt64(value int64) RedisParameter {
	return RedisParameter{RedisParameterInt64, value}
}
func MakeRedisParameterBinary(value []uint8) RedisParameter {
	return RedisParameter{RedisParameterBinary, value}
}

const (
	RedisResultNil    uint8 = 0
	RedisResultStatus uint8 = 1
	RedisResultInt64  uint8 = 2
	RedisResultBinary uint8 = 3
)

// A return type for the general-purpose `execute` function.
type RedisResult struct {
	tag   uint8
	value any
}

func (self RedisResult) Tag() uint8 {
	return self.tag
}

func (self RedisResult) Status() string {
	if self.tag != RedisResultStatus {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self RedisResult) Int64() int64 {
	if self.tag != RedisResultInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self RedisResult) Binary() []uint8 {
	if self.tag != RedisResultBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeRedisResultNil() RedisResult {
	return RedisResult{RedisResultNil, nil}
}
func MakeRedisResultStatus(value string) RedisResult {
	return RedisResult{RedisResultStatus, value}
}
func MakeRedisResultInt64(value int64) RedisResult {
	return RedisResult{RedisResultInt64, value}
}
func MakeRedisResultBinary(value []uint8) RedisResult {
	return RedisResult{RedisResultBinary, value}
}
