// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_cli_0_2_0_terminal_input

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"runtime"
)

//go:wasmimport wasi:cli/terminal-input@0.2.0 [resource-drop]terminal-input
func resourceDropTerminalInput(handle int32)

// The input side of a terminal.
type TerminalInput struct {
	handle *wit_runtime.Handle
}

func (self *TerminalInput) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *TerminalInput) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *TerminalInput) Handle() int32 {
	return self.handle.Use()
}

func (self *TerminalInput) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTerminalInput(handle)
	}
}

func TerminalInputFromOwnHandle(handleValue int32) *TerminalInput {
	handle := wit_runtime.MakeHandle(handleValue)
	value := &TerminalInput{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropTerminalInput(handleValue)
		}
	}, 0)
	return value
}

func TerminalInputFromBorrowHandle(handleValue int32) *TerminalInput {
	return TerminalInputFromOwnHandle(handleValue)
}
