// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_keyvalue_store

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
)

const (
	// The host does not recognize the store identifier requested.
	ErrorNoSuchStore uint8 = 0
	// The requesting component does not have access to the specified store
	// (which may or may not exist).
	ErrorAccessDenied uint8 = 1
	// Some implementation-specific error has occurred (e.g. I/O)
	ErrorOther uint8 = 2
)

// The set of errors which may be raised by functions in this package
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorNoSuchStore() Error {
	return Error{ErrorNoSuchStore, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

// A response to a `list-keys` operation.
type KeyResponse struct {
	// The list of keys returned by the query.
	Keys []string
	// The continuation token to use to fetch the next page of keys. If this is `null`, then
	// there are no more keys to fetch.
	Cursor wit_types.Option[string]
}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [resource-drop]bucket
func resourceDropBucket(handle int32)

// A bucket is a collection of key-value pairs. Each key-value pair is stored as a entry in the
// bucket, and the bucket itself acts as a collection of all these entries.
//
// It is worth noting that the exact terminology for bucket in key-value stores can very
// depending on the specific implementation. For example:
//
// 1. Amazon DynamoDB calls a collection of key-value pairs a table
// 2. Redis has hashes, sets, and sorted sets as different types of collections
// 3. Cassandra calls a collection of key-value pairs a column family
// 4. MongoDB calls a collection of key-value pairs a collection
// 5. Riak calls a collection of key-value pairs a bucket
// 6. Memcached calls a collection of key-value pairs a slab
// 7. Azure Cosmos DB calls a collection of key-value pairs a container
//
// In this interface, we use the term `bucket` to refer to a collection of key-value pairs
type Bucket struct {
	handle *wit_runtime.Handle
}

func (self *Bucket) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Bucket) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Bucket) Handle() int32 {
	return self.handle.Use()
}

func (self *Bucket) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropBucket(handle)
	}
}

func BucketFromOwnHandle(handleValue int32) *Bucket {
	handle := wit_runtime.MakeHandle(handleValue)
	value := &Bucket{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropBucket(handleValue)
		}
	}, 0)
	return value
}

func BucketFromBorrowHandle(handleValue int32) *Bucket {
	return BucketFromOwnHandle(handleValue)
}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 open
func wasm_import_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Open(identifier string) wit_types.Result[*Bucket, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(identifier))
	pinner.Pin(utf8)
	wasm_import_open(uintptr(utf8), uint32(len(identifier)), returnArea)
	var result wit_types.Result[*Bucket, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[*Bucket, Error](BucketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[*Bucket, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.get
func wasm_import_method_bucket_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Get(key string) wit_types.Result[wit_types.Option[[]uint8], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_get((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result wit_types.Result[wit_types.Option[[]uint8], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option wit_types.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = wit_types.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			option = wit_types.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = wit_types.Ok[wit_types.Option[[]uint8], Error](option)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Option[[]uint8], Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.set
func wasm_import_method_bucket_set(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Bucket) Set(key string, value []uint8) wit_types.Result[wit_types.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_method_bucket_set((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result wit_types.Result[wit_types.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[wit_types.Unit, Error](wit_types.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.delete
func wasm_import_method_bucket_delete(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Delete(key string) wit_types.Result[wit_types.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_delete((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result wit_types.Result[wit_types.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[wit_types.Unit, Error](wit_types.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.exists
func wasm_import_method_bucket_exists(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Bucket) Exists(key string) wit_types.Result[bool, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_bucket_exists((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result wit_types.Result[bool, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[bool, Error]((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) != 0))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[bool, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport wasi:keyvalue/store@0.2.0-draft2 [method]bucket.list-keys
func wasm_import_method_bucket_list_keys(arg0 int32, arg1 int32, arg2 uintptr, arg3 uint32, arg4 uintptr)

func (self *Bucket) ListKeys(cursor wit_types.Option[string]) wit_types.Result[KeyResponse, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (6 * 4), 4))
	var option int32
	var option0 uintptr
	var option1 uint32
	switch cursor.Tag() {
	case wit_types.OptionNone:

		option = int32(0)
		option0 = 0
		option1 = 0
	case wit_types.OptionSome:
		payload := cursor.Some()
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)

		option = int32(1)
		option0 = uintptr(utf8)
		option1 = uint32(len(payload))
	default:
		panic("unreachable")
	}
	wasm_import_method_bucket_list_keys((self).Handle(), option, option0, option1, returnArea)
	var result5 wit_types.Result[KeyResponse, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		var option3 wit_types.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))) {
		case 0:

			option3 = wit_types.None[string]()
		case 1:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (5 * 4))))

			option3 = wit_types.Some[string](value2)
		default:
			panic("unreachable")
		}

		result5 = wit_types.Ok[KeyResponse, Error](KeyResponse{result, option3})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchStore()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value4)

		default:
			panic("unreachable")
		}

		result5 = wit_types.Err[KeyResponse, Error](variant)
	default:
		panic("unreachable")
	}
	result6 := result5
	return result6

}
