// Code generated by wit-bindgen-go. DO NOT EDIT.

package batch

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:keyvalue@0.2.0-draft2".

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 get-many
//go:noescape
func wasmimport_GetMany(bucket0 uint32, keys0 *string, keys1 uint32, result *cm.Result[ErrorShape, cm.List[cm.Tuple[string, cm.Option[cm.List[uint8]]]], Error])

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 set-many
//go:noescape
func wasmimport_SetMany(bucket0 uint32, keyValues0 *cm.Tuple[string, cm.List[uint8]], keyValues1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport wasi:keyvalue/batch@0.2.0-draft2 delete-many
//go:noescape
func wasmimport_DeleteMany(bucket0 uint32, keys0 *string, keys1 uint32, result *cm.Result[Error, struct{}, Error])
