// Code generated by wit-bindgen-go. DO NOT EDIT.

package mysql

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// RowSetShape is used for storage in variant or result types.
type RowSetShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(RowSet{})]byte
}
