// Code generated by wit-bindgen-go. DO NOT EDIT.

package store

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:config@0.2.0-draft-2024-09-27".

//go:wasmimport wasi:config/store@0.2.0-draft-2024-09-27 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Result[OptionStringShape, cm.Option[string], Error])

//go:wasmimport wasi:config/store@0.2.0-draft-2024-09-27 get-all
//go:noescape
func wasmimport_GetAll(result *cm.Result[ErrorShape, cm.List[[2]string], Error])
