// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:clocks@0.3.0-rc-2026-03-15
//     wasi:filesystem@0.3.0-rc-2026-03-15
//     wasi:sockets@0.3.0-rc-2026-03-15
//     wasi:random@0.3.0-rc-2026-03-15
//     wasi:cli@0.3.0-rc-2026-03-15
//     wasi:http@0.2.0-rc-2023-11-10
//     wasi:http@0.3.0-rc-2026-03-15
//     componentize-go:union

package fermyon_spin_mysql

import (
	"github.com/spinframework/spin-go-sdk/v3/imports/fermyon_spin_rdbms_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type ParameterValue = fermyon_spin_rdbms_types.ParameterValue
type RowSet = fermyon_spin_rdbms_types.RowSet

const (
	MysqlErrorSuccess               uint8 = 0
	MysqlErrorConnectionFailed      uint8 = 1
	MysqlErrorBadParameter          uint8 = 2
	MysqlErrorQueryFailed           uint8 = 3
	MysqlErrorValueConversionFailed uint8 = 4
	MysqlErrorOtherError            uint8 = 5
)

// General purpose error.
type MysqlError struct {
	tag   uint8
	value any
}

func (self MysqlError) Tag() uint8 {
	return self.tag
}

func (self MysqlError) ConnectionFailed() string {
	if self.tag != MysqlErrorConnectionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self MysqlError) BadParameter() string {
	if self.tag != MysqlErrorBadParameter {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self MysqlError) QueryFailed() string {
	if self.tag != MysqlErrorQueryFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self MysqlError) ValueConversionFailed() string {
	if self.tag != MysqlErrorValueConversionFailed {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self MysqlError) OtherError() string {
	if self.tag != MysqlErrorOtherError {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeMysqlErrorSuccess() MysqlError {
	return MysqlError{MysqlErrorSuccess, nil}
}
func MakeMysqlErrorConnectionFailed(value string) MysqlError {
	return MysqlError{MysqlErrorConnectionFailed, value}
}
func MakeMysqlErrorBadParameter(value string) MysqlError {
	return MysqlError{MysqlErrorBadParameter, value}
}
func MakeMysqlErrorQueryFailed(value string) MysqlError {
	return MysqlError{MysqlErrorQueryFailed, value}
}
func MakeMysqlErrorValueConversionFailed(value string) MysqlError {
	return MysqlError{MysqlErrorValueConversionFailed, value}
}
func MakeMysqlErrorOtherError(value string) MysqlError {
	return MysqlError{MysqlErrorOtherError, value}
}

//go:wasmimport fermyon:spin/mysql query
func wasm_import_query(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Query(address string, statement string, params []fermyon_spin_rdbms_types.ParameterValue) witTypes.Result[fermyon_spin_rdbms_types.RowSet, MysqlError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf80)
	slice := params
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(8+2*4))

		switch element.Tag() {
		case fermyon_spin_rdbms_types.ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case fermyon_spin_rdbms_types.ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case fermyon_spin_rdbms_types.ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case fermyon_spin_rdbms_types.ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

		case fermyon_spin_rdbms_types.ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case fermyon_spin_rdbms_types.ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_query(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(statement)), uintptr(result2), length, returnArea)
	var result14 witTypes.Result[fermyon_spin_rdbms_types.RowSet, MysqlError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result3 := make([]fermyon_spin_rdbms_types.Column, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(3*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result3 = append(result3, fermyon_spin_rdbms_types.Column{value, uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))})
		}

		result7 := make([][]fermyon_spin_rdbms_types.DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(2*4))
			result6 := make([]fermyon_spin_rdbms_types.DbValue, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*(8+2*4))
				var variant fermyon_spin_rdbms_types.DbValue
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
				case 0:

					variant = fermyon_spin_rdbms_types.MakeDbValueBoolean((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) != 0))

				case 1:

					variant = fermyon_spin_rdbms_types.MakeDbValueInt8(int8(int8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 2:

					variant = fermyon_spin_rdbms_types.MakeDbValueInt16(int16(int16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 3:

					variant = fermyon_spin_rdbms_types.MakeDbValueInt32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 4:

					variant = fermyon_spin_rdbms_types.MakeDbValueInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 5:

					variant = fermyon_spin_rdbms_types.MakeDbValueUint8(uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 6:

					variant = fermyon_spin_rdbms_types.MakeDbValueUint16(uint16(uint16(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))))

				case 7:

					variant = fermyon_spin_rdbms_types.MakeDbValueUint32(uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))))

				case 8:

					variant = fermyon_spin_rdbms_types.MakeDbValueUint64(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8))))

				case 9:

					variant = fermyon_spin_rdbms_types.MakeDbValueFloating32(*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 10:

					variant = fermyon_spin_rdbms_types.MakeDbValueFloating64(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 11:
					value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = fermyon_spin_rdbms_types.MakeDbValueStr(value4)

				case 12:
					value5 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = fermyon_spin_rdbms_types.MakeDbValueBinary(value5)

				case 13:

					variant = fermyon_spin_rdbms_types.MakeDbValueDbNull()

				case 14:

					variant = fermyon_spin_rdbms_types.MakeDbValueUnsupported()

				default:
					panic("unreachable")
				}

				result6 = append(result6, variant)
			}

			result7 = append(result7, result6)
		}

		result14 = witTypes.Ok[fermyon_spin_rdbms_types.RowSet, MysqlError](fermyon_spin_rdbms_types.RowSet{result3, result7})
	case 1:
		var variant13 MysqlError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant13 = MakeMysqlErrorSuccess()

		case 1:
			value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant13 = MakeMysqlErrorConnectionFailed(value8)

		case 2:
			value9 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant13 = MakeMysqlErrorBadParameter(value9)

		case 3:
			value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant13 = MakeMysqlErrorQueryFailed(value10)

		case 4:
			value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant13 = MakeMysqlErrorValueConversionFailed(value11)

		case 5:
			value12 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant13 = MakeMysqlErrorOtherError(value12)

		default:
			panic("unreachable")
		}

		result14 = witTypes.Err[fermyon_spin_rdbms_types.RowSet, MysqlError](variant13)
	default:
		panic("unreachable")
	}
	result15 := result14
	return result15

}

//go:wasmimport fermyon:spin/mysql execute
func wasm_import_execute(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32, arg6 uintptr)

func Execute(address string, statement string, params []fermyon_spin_rdbms_types.ParameterValue) witTypes.Result[witTypes.Unit, MysqlError] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	utf80 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf80)
	slice := params
	length := uint32(len(slice))
	result2 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result2, index*(8+2*4))

		switch element.Tag() {
		case fermyon_spin_rdbms_types.ParameterValueBoolean:
			payload := element.Boolean()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case fermyon_spin_rdbms_types.ParameterValueInt8:
			payload := element.Int8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueInt16:
			payload := element.Int16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueInt32:
			payload := element.Int32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueUint8:
			payload := element.Uint8()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(5))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueUint16:
			payload := element.Uint16()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(6))
			*(*int16)(unsafe.Add(unsafe.Pointer(base), 8)) = int16(int32(payload))

		case fermyon_spin_rdbms_types.ParameterValueUint32:
			payload := element.Uint32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(7))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 8)) = int32(payload)

		case fermyon_spin_rdbms_types.ParameterValueUint64:
			payload := element.Uint64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(8))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case fermyon_spin_rdbms_types.ParameterValueFloating32:
			payload := element.Floating32()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(9))
			*(*float32)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueFloating64:
			payload := element.Floating64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(10))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case fermyon_spin_rdbms_types.ParameterValueStr:
			payload := element.Str()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(11))
			utf81 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf81)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf81)))

		case fermyon_spin_rdbms_types.ParameterValueBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(12))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case fermyon_spin_rdbms_types.ParameterValueDbNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(13))

		default:
			panic("unreachable")
		}

	}

	wasm_import_execute(uintptr(utf8), uint32(len(address)), uintptr(utf80), uint32(len(statement)), uintptr(result2), length, returnArea)
	var result7 witTypes.Result[witTypes.Unit, MysqlError]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result7 = witTypes.Ok[witTypes.Unit, MysqlError](witTypes.Unit{})
	case 1:
		var variant MysqlError
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeMysqlErrorSuccess()

		case 1:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMysqlErrorConnectionFailed(value)

		case 2:
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMysqlErrorBadParameter(value3)

		case 3:
			value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMysqlErrorQueryFailed(value4)

		case 4:
			value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMysqlErrorValueConversionFailed(value5)

		case 5:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeMysqlErrorOtherError(value6)

		default:
			panic("unreachable")
		}

		result7 = witTypes.Err[witTypes.Unit, MysqlError](variant)
	default:
		panic("unreachable")
	}
	result8 := result7
	return result8

}
