// Code generated by wit-bindgen-go. DO NOT EDIT.

package postgres

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// RowSetShape is used for storage in variant or result types.
type RowSetShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(RowSet{})]byte
}

// PgErrorShape is used for storage in variant or result types.
type PgErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(PgError{})]byte
}
