// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package wasi_cli_0_2_0_terminal_stdout

import (
	"github.com/spinframework/spin-go-sdk/v3/internal/wasi_cli_0_2_0_terminal_output"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type TerminalOutput = wasi_cli_0_2_0_terminal_output.TerminalOutput

//go:wasmimport wasi:cli/terminal-stdout@0.2.0 get-terminal-stdout
func wasm_import_get_terminal_stdout(arg0 uintptr)

func GetTerminalStdout() witTypes.Option[*wasi_cli_0_2_0_terminal_output.TerminalOutput] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_get_terminal_stdout(returnArea)
	var option witTypes.Option[*wasi_cli_0_2_0_terminal_output.TerminalOutput]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[*wasi_cli_0_2_0_terminal_output.TerminalOutput]()
	case 1:

		option = witTypes.Some[*wasi_cli_0_2_0_terminal_output.TerminalOutput](wasi_cli_0_2_0_terminal_output.TerminalOutputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
