// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package fermyon_spin_2_0_0_sqlite

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

//go:wasmimport fermyon:spin/sqlite@2.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

// A handle to an open sqlite instance
type Connection struct {
	handle *witRuntime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	handle := witRuntime.MakeHandle(handleValue)
	return &Connection{handle}
}

const (
	// The host does not recognize the database name requested.
	ErrorNoSuchDatabase uint8 = 0
	// The requesting component does not have access to the specified database (which may or may not exist).
	ErrorAccessDenied uint8 = 1
	// The provided connection is not valid
	ErrorInvalidConnection uint8 = 2
	// The database has reached its capacity
	ErrorDatabaseFull uint8 = 3
	// Some implementation-specific error has occurred (e.g. I/O)
	ErrorIo uint8 = 4
)

// The set of errors which may be raised by functions in this interface
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Io() string {
	if self.tag != ErrorIo {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorNoSuchDatabase() Error {
	return Error{ErrorNoSuchDatabase, nil}
}
func MakeErrorAccessDenied() Error {
	return Error{ErrorAccessDenied, nil}
}
func MakeErrorInvalidConnection() Error {
	return Error{ErrorInvalidConnection, nil}
}
func MakeErrorDatabaseFull() Error {
	return Error{ErrorDatabaseFull, nil}
}
func MakeErrorIo(value string) Error {
	return Error{ErrorIo, value}
}

const (
	ValueInteger uint8 = 0
	ValueReal    uint8 = 1
	ValueText    uint8 = 2
	ValueBlob    uint8 = 3
	ValueNull    uint8 = 4
)

// A single column's result from a database query
type Value struct {
	tag   uint8
	value any
}

func (self Value) Tag() uint8 {
	return self.tag
}

func (self Value) Integer() int64 {
	if self.tag != ValueInteger {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self Value) Real() float64 {
	if self.tag != ValueReal {
		panic("tag mismatch")
	}
	return self.value.(float64)
}
func (self Value) Text() string {
	if self.tag != ValueText {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Value) Blob() []uint8 {
	if self.tag != ValueBlob {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeValueInteger(value int64) Value {
	return Value{ValueInteger, value}
}
func MakeValueReal(value float64) Value {
	return Value{ValueReal, value}
}
func MakeValueText(value string) Value {
	return Value{ValueText, value}
}
func MakeValueBlob(value []uint8) Value {
	return Value{ValueBlob, value}
}
func MakeValueNull() Value {
	return Value{ValueNull, nil}
}

// A set of values for each of the columns in a query-result
type RowResult struct {
	Values []Value
}

// A result of a query
type QueryResult struct {
	// The names of the columns retrieved in the query
	Columns []string
	// the row results each containing the values for all the columns for a given row
	Rows []RowResult
}

//go:wasmimport fermyon:spin/sqlite@2.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func ConnectionOpen(database string) witTypes.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(database))
	pinner.Pin(utf8)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(database)), returnArea)
	var result witTypes.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorNoSuchDatabase()

		case 1:

			variant = MakeErrorAccessDenied()

		case 2:

			variant = MakeErrorInvalidConnection()

		case 3:

			variant = MakeErrorDatabaseFull()

		case 4:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorIo(value)

		default:
			panic("unreachable")
		}

		result = witTypes.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/sqlite@2.0.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Execute(statement string, parameters []Value) witTypes.Result[QueryResult, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (5 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(statement))
	pinner.Pin(utf8)
	slice := parameters
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+2*4))

		switch element.Tag() {
		case ValueInteger:
			payload := element.Integer()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueReal:
			payload := element.Real()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case ValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case ValueBlob:
			payload := element.Blob()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		case ValueNull:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(statement)), uintptr(result), length, returnArea)
	var result8 witTypes.Result[QueryResult, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result1 = append(result1, value)
		}

		result5 := make([]RowResult, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))), index*(2*4))
			result4 := make([]Value, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
				base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*(8+2*4))
				var variant Value
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
				case 0:

					variant = MakeValueInteger(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 1:

					variant = MakeValueReal(*(*float64)(unsafe.Add(unsafe.Pointer(base), 8)))

				case 2:
					value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeValueText(value2)

				case 3:
					value3 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

					variant = MakeValueBlob(value3)

				case 4:

					variant = MakeValueNull()

				default:
					panic("unreachable")
				}

				result4 = append(result4, variant)
			}

			result5 = append(result5, RowResult{result4})
		}

		result8 = witTypes.Ok[QueryResult, Error](QueryResult{result1, result5})
	case 1:
		var variant7 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant7 = MakeErrorNoSuchDatabase()

		case 1:

			variant7 = MakeErrorAccessDenied()

		case 2:

			variant7 = MakeErrorInvalidConnection()

		case 3:

			variant7 = MakeErrorDatabaseFull()

		case 4:
			value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant7 = MakeErrorIo(value6)

		default:
			panic("unreachable")
		}

		result8 = witTypes.Err[QueryResult, Error](variant7)
	default:
		panic("unreachable")
	}
	result9 := result8
	return result9

}
