spin_manifest_version = 2

[application]
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "A simple Spin application written in (Tiny)Go."
name = "hello-kv"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "main.wasm"
key_value_stores = ["default"]
[component.hello.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/spinframework/spin-go-sdk/v3)/wit --wit-world http-trigger -gc=leaking -no-debug -o main.wasm main.go"

