// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     fermyon:spin
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:cli@0.2.0
//     wasi:http@0.2.0
//     wasi:io@0.2.0-rc-2023-10-18
//     wasi:clocks@0.2.0-rc-2023-10-18
//     wasi:random@0.2.0-rc-2023-10-18
//     wasi:filesystem@0.2.0-rc-2023-10-18
//     wasi:sockets@0.2.0-rc-2023-10-18
//     wasi:cli@0.2.0-rc-2023-10-18
//     wasi:http@0.2.0-rc-2023-10-18
//     fermyon:spin@2.0.0
//     wasi:keyvalue@0.2.0-draft2
//     spin:postgres@3.0.0
//     wasi:config@0.2.0-draft-2024-09-27
//     fermyon:spin@3.0.0
//     wasi:io@0.2.0-rc-2023-11-10
//     wasi:clocks@0.2.0-rc-2023-11-10
//     wasi:filesystem@0.2.0-rc-2023-11-10
//     wasi:sockets@0.2.0-rc-2023-11-10
//     wasi:random@0.2.0-rc-2023-11-10
//     wasi:cli@0.2.0-rc-2023-11-10
//     wasi:http@0.2.0-rc-2023-11-10

package fermyon_spin_2_0_0_redis

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
)

const (
	// An invalid address string
	ErrorInvalidAddress uint8 = 0
	// There are too many open connections
	ErrorTooManyConnections uint8 = 1
	// A retrieved value was not of the correct type
	ErrorTypeError uint8 = 2
	// Some other error occurred
	ErrorOther uint8 = 3
)

// Errors related to interacting with Redis
type Error struct {
	tag   uint8
	value any
}

func (self Error) Tag() uint8 {
	return self.tag
}

func (self Error) Other() string {
	if self.tag != ErrorOther {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeErrorInvalidAddress() Error {
	return Error{ErrorInvalidAddress, nil}
}
func MakeErrorTooManyConnections() Error {
	return Error{ErrorTooManyConnections, nil}
}
func MakeErrorTypeError() Error {
	return Error{ErrorTypeError, nil}
}
func MakeErrorOther(value string) Error {
	return Error{ErrorOther, value}
}

//go:wasmimport fermyon:spin/redis@2.0.0 [resource-drop]connection
func resourceDropConnection(handle int32)

type Connection struct {
	handle *wit_runtime.Handle
}

func (self *Connection) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Connection) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Connection) Handle() int32 {
	return self.handle.Use()
}

func (self *Connection) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropConnection(handle)
	}
}

func ConnectionFromOwnHandle(handleValue int32) *Connection {
	handle := wit_runtime.MakeHandle(handleValue)
	value := &Connection{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropConnection(handleValue)
		}
	}, 0)
	return value
}

func ConnectionFromBorrowHandle(handleValue int32) *Connection {
	return ConnectionFromOwnHandle(handleValue)
}

// The message payload.
type Payload = []uint8

const (
	RedisParameterInt64  uint8 = 0
	RedisParameterBinary uint8 = 1
)

// A parameter type for the general-purpose `execute` function.
type RedisParameter struct {
	tag   uint8
	value any
}

func (self RedisParameter) Tag() uint8 {
	return self.tag
}

func (self RedisParameter) Int64() int64 {
	if self.tag != RedisParameterInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self RedisParameter) Binary() []uint8 {
	if self.tag != RedisParameterBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeRedisParameterInt64(value int64) RedisParameter {
	return RedisParameter{RedisParameterInt64, value}
}
func MakeRedisParameterBinary(value []uint8) RedisParameter {
	return RedisParameter{RedisParameterBinary, value}
}

const (
	RedisResultNil    uint8 = 0
	RedisResultStatus uint8 = 1
	RedisResultInt64  uint8 = 2
	RedisResultBinary uint8 = 3
)

// A return type for the general-purpose `execute` function.
type RedisResult struct {
	tag   uint8
	value any
}

func (self RedisResult) Tag() uint8 {
	return self.tag
}

func (self RedisResult) Status() string {
	if self.tag != RedisResultStatus {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self RedisResult) Int64() int64 {
	if self.tag != RedisResultInt64 {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self RedisResult) Binary() []uint8 {
	if self.tag != RedisResultBinary {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeRedisResultNil() RedisResult {
	return RedisResult{RedisResultNil, nil}
}
func MakeRedisResultStatus(value string) RedisResult {
	return RedisResult{RedisResultStatus, value}
}
func MakeRedisResultInt64(value int64) RedisResult {
	return RedisResult{RedisResultInt64, value}
}
func MakeRedisResultBinary(value []uint8) RedisResult {
	return RedisResult{RedisResultBinary, value}
}

//go:wasmimport fermyon:spin/redis@2.0.0 [static]connection.open
func wasm_import_static_connection_open(arg0 uintptr, arg1 uint32, arg2 uintptr)

func ConnectionOpen(address string) wit_types.Result[*Connection, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(address))
	pinner.Pin(utf8)
	wasm_import_static_connection_open(uintptr(utf8), uint32(len(address)), returnArea)
	var result wit_types.Result[*Connection, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[*Connection, Error](ConnectionFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[*Connection, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.publish
func wasm_import_method_connection_publish(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Publish(channel string, payload []uint8) wit_types.Result[wit_types.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(channel))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(payload))
	pinner.Pin(data)
	wasm_import_method_connection_publish((self).Handle(), uintptr(utf8), uint32(len(channel)), uintptr(data), uint32(len(payload)), returnArea)
	var result wit_types.Result[wit_types.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[wit_types.Unit, Error](wit_types.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.get
func wasm_import_method_connection_get(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Connection) Get(key string) wit_types.Result[wit_types.Option[[]uint8], Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_connection_get((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result wit_types.Result[wit_types.Option[[]uint8], Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		var option wit_types.Option[[]uint8]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			option = wit_types.None[[]uint8]()
		case 1:
			value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			option = wit_types.Some[[]uint8](value)
		default:
			panic("unreachable")
		}

		result = wit_types.Ok[wit_types.Option[[]uint8], Error](option)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Option[[]uint8], Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.set
func wasm_import_method_connection_set(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Set(key string, value []uint8) wit_types.Result[wit_types.Unit, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	data := unsafe.Pointer(unsafe.SliceData(value))
	pinner.Pin(data)
	wasm_import_method_connection_set((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(data), uint32(len(value)), returnArea)
	var result wit_types.Result[wit_types.Unit, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[wit_types.Unit, Error](wit_types.Unit{})
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[wit_types.Unit, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result
	return result1

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.incr
func wasm_import_method_connection_incr(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Connection) Incr(key string) wit_types.Result[int64, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_connection_incr((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result wit_types.Result[int64, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = wit_types.Ok[int64, Error](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 8)))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result = wit_types.Err[int64, Error](variant)
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.del
func wasm_import_method_connection_del(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Connection) Del(keys []string) wit_types.Result[uint32, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	slice := keys
	length := uint32(len(slice))
	result := wit_runtime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	wasm_import_method_connection_del((self).Handle(), uintptr(result), length, returnArea)
	var result0 wit_types.Result[uint32, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result0 = wit_types.Ok[uint32, Error](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result0 = wit_types.Err[uint32, Error](variant)
	default:
		panic("unreachable")
	}
	result1 := result0
	return result1

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.sadd
func wasm_import_method_connection_sadd(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Sadd(key string, values []string) wit_types.Result[uint32, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	slice := values
	length := uint32(len(slice))
	result := wit_runtime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf80 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))

	}

	wasm_import_method_connection_sadd((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(result), length, returnArea)
	var result1 wit_types.Result[uint32, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result1 = wit_types.Ok[uint32, Error](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result1 = wit_types.Err[uint32, Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.smembers
func wasm_import_method_connection_smembers(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Connection) Smembers(key string) wit_types.Result[[]string, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_method_connection_smembers((self).Handle(), uintptr(utf8), uint32(len(key)), returnArea)
	var result1 wit_types.Result[[]string, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result1 = wit_types.Ok[[]string, Error](result)
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value0)

		default:
			panic("unreachable")
		}

		result1 = wit_types.Err[[]string, Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.srem
func wasm_import_method_connection_srem(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Srem(key string, values []string) wit_types.Result[uint32, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	slice := values
	length := uint32(len(slice))
	result := wit_runtime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(2*4))
		utf80 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))

	}

	wasm_import_method_connection_srem((self).Handle(), uintptr(utf8), uint32(len(key)), uintptr(result), length, returnArea)
	var result1 wit_types.Result[uint32, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result1 = wit_types.Ok[uint32, Error](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))
	case 1:
		var variant Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant = MakeErrorInvalidAddress()

		case 1:

			variant = MakeErrorTooManyConnections()

		case 2:

			variant = MakeErrorTypeError()

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant = MakeErrorOther(value)

		default:
			panic("unreachable")
		}

		result1 = wit_types.Err[uint32, Error](variant)
	default:
		panic("unreachable")
	}
	result2 := result1
	return result2

}

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.execute
func wasm_import_method_connection_execute(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32, arg5 uintptr)

func (self *Connection) Execute(command string, arguments []RedisParameter) wit_types.Result[[]RedisResult, Error] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(wit_runtime.Allocate(pinner, (4 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(command))
	pinner.Pin(utf8)
	slice := arguments
	length := uint32(len(slice))
	result := wit_runtime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result, index*(8+2*4))

		switch element.Tag() {
		case RedisParameterInt64:
			payload := element.Int64()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case RedisParameterBinary:
			payload := element.Binary()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		default:
			panic("unreachable")
		}

	}

	wasm_import_method_connection_execute((self).Handle(), uintptr(utf8), uint32(len(command)), uintptr(result), length, returnArea)
	var result4 wit_types.Result[[]RedisResult, Error]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:
		result1 := make([]RedisResult, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))), index*(8+2*4))
			var variant RedisResult
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))) {
			case 0:

				variant = MakeRedisResultNil()

			case 1:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant = MakeRedisResultStatus(value)

			case 2:

				variant = MakeRedisResultInt64(*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)))

			case 3:
				value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

				variant = MakeRedisResultBinary(value0)

			default:
				panic("unreachable")
			}

			result1 = append(result1, variant)
		}

		result4 = wit_types.Ok[[]RedisResult, Error](result1)
	case 1:
		var variant3 Error
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))) {
		case 0:

			variant3 = MakeErrorInvalidAddress()

		case 1:

			variant3 = MakeErrorTooManyConnections()

		case 2:

			variant3 = MakeErrorTypeError()

		case 3:
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4))))

			variant3 = MakeErrorOther(value2)

		default:
			panic("unreachable")
		}

		result4 = wit_types.Err[[]RedisResult, Error](variant3)
	default:
		panic("unreachable")
	}
	result5 := result4
	return result5

}
