// Code generated by wit-bindgen-go. DO NOT EDIT.

package postgres

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TupleS32U8U8U8U8U8U32Shape is used for storage in variant or result types.
type TupleS32U8U8U8U8U8U32Shape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Tuple7[int32, uint8, uint8, uint8, uint8, uint8, uint32]{})]byte
}

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

// RowSetShape is used for storage in variant or result types.
type RowSetShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(RowSet{})]byte
}
