name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install componentize-go
        # TODO: Switch to an upstream (pre-built) release once new one is
        # available and includes the following PRs:
        # https://github.com/bytecodealliance/componentize-go/pull/35
        # https://github.com/bytecodealliance/componentize-go/pull/36
        # https://github.com/bytecodealliance/componentize-go/pull/37
        run: |
          curl -LO https://github.com/dicej/componentize-go/releases/download/canary/componentize-go-linux-amd64.tar.gz
          tar xf componentize-go-linux-amd64.tar.gz
          chmod +x componentize-go
          pwd >> $GITHUB_PATH

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          # TODO: Switch to Spin 4.0 when it's available
           version: "canary"

      - name: Run integration tests
        run: go test -v -count=1 .
