name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install latest Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install componentize-go
        # TODO: Switch to pre-built release once new one is available (i.e. post-v0.2.0):
        run: cargo install --locked --git https://github.com/bytecodealliance/componentize-go --rev 94413331

      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v3.6.2"

      - name: Run integration tests
        run: make test-integration
