name: Run Integration tests
on:
  pull_request:
    branches:
      - wasip2

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup componentize-go
        run: |
          curl -LO https://github.com/asteurer/componentize-go/releases/download/v0.2.0/componentize-go-linux-amd64.tar.gz
          echo "27fc32998f023a88a6a1f44524631a705163f23ce2a02fc14987726897360027  componentize-go-linux-amd64.tar.gz" | sha256sum --check
          tar -xf componentize-go-linux-amd64.tar.gz
          chmod +x componentize-go
          mkdir -p $HOME/.local/bin
          mv componentize-go $HOME/.local/bin/componentize-go
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v3.5.1"

      - name: Run wasip2 integration tests
        run: make test-integration-wasip2

